@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "AMF"
participant "AUSF"
participant "UDM"


"AMF" -> "AUSF": 60, HTTP/2 req.\nPOST  /nausf-auth/v1/ue-authentications

note right #03B5AA
**AMF to AUSF**
end note

"AMF" -> "AUSF": 62, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to AUSF**
10.0.3.1 to 10.0.4.1 (IPs)
HTTP/2 stream 1 payload
{
  "supiOrSuci": "suci-0-901-70-0000-0-0-0000000004",
  "servingNetworkName": "5G:mnc070.mcc901.3gppnetwork.org"
}

end note

"AUSF" -> "UDM": 84, HTTP/2 req.\nPOST  /nudm-ueau/v1/suci-0-901-70-0000-0-0-0000000004/security-information/generate-auth-data

note right #03B5AA
**AUSF to UDM**
end note

"AUSF" -> "UDM": 88, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AUSF to UDM**
10.0.4.1 to 10.0.15.1 (IPs)
HTTP/2 stream 1 payload
{
  "servingNetworkName": "5G:mnc070.mcc901.3gppnetwork.org",
  "ausfInstanceId": "491ee058-f5bb-41ed-bcef-5dbf2ad79138"
}

end note

"UDM" -> "AUSF": 91, HTTP/2 200 rsp.

note right #D7FEFC
**UDM to AUSF**
end note

"UDM" -> "AUSF": 92, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDM to AUSF**
10.0.15.1 to 10.0.4.1 (IPs)
HTTP/2 stream 1 payload
{
  "authType": "5G_AKA",
  "authenticationVector": {
    "avType": "5G_HE_AKA",
    "rand": "92415a275507815136fac9526a3a05ce",
    "autn": "a8b846057ebe8000e23edaf5819b082e",
    "xresStar": "80ce997efa978ca55c9037401cf0fa73",
    "kausf": "e1c2575d5057fdc84d6008f50533091fa8c69d32e3b516dd893a1ac4d9f3c73f"
  }
}

end note

"AUSF" -> "AMF": 95, HTTP/2 201 rsp.

note right #D7FEFC
**AUSF to AMF**
end note

"AUSF" -> "AMF": 96, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AUSF to AMF**
10.0.4.1 to 10.0.3.1 (IPs)
HTTP/2 stream 1 payload
{
  "authType": "5G_AKA",
  "5gAuthData": {
    "rand": "92415a275507815136fac9526a3a05ce",
    "hxresStar": "132bc5c1cd6493517ad62d69327c8e58",
    "autn": "a8b846057ebe8000e23edaf5819b082e"
  },
  "_links": {
    "5g-aka": {
      "href": "http://10.0.4.1:7777/nausf-auth/v1/ue-authentications/1/5g-aka-confirmation"
    }
  }
}

end note

"AMF" -> "AUSF": 98, HTTP/2 req.\nPUT  /nausf-auth/v1/ue-authentications/1/5g-aka-confirmation

note right #03B5AA
**AMF to AUSF**
end note

"AMF" -> "AUSF": 100, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to AUSF**
10.0.3.1 to 10.0.4.1 (IPs)
HTTP/2 stream 3 payload
{
  "resStar": "80ce997efa978ca55c9037401cf0fa73"
}

end note

"AUSF" -> "UDM": 102, HTTP/2 req.\nPOST  /nudm-ueau/v1/imsi-901700000000004/auth-events

note right #03B5AA
**AUSF to UDM**
end note

"AUSF" -> "UDM": 104, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AUSF to UDM**
10.0.4.1 to 10.0.15.1 (IPs)
HTTP/2 stream 3 payload
{
  "nfInstanceId": "491ee058-f5bb-41ed-bcef-5dbf2ad79138",
  "success": true,
  "timeStamp": "2023-05-18T22:58:22.917351+02:00",
  "authType": "5G_AKA",
  "servingNetworkName": "5G:mnc070.mcc901.3gppnetwork.org"
}

end note

"UDM" -> "AUSF": 106, HTTP/2 201 rsp.

note right #D7FEFC
**UDM to AUSF**
end note

"UDM" -> "AUSF": 107, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDM to AUSF**
10.0.15.1 to 10.0.4.1 (IPs)
HTTP/2 stream 3 payload
{
  "nfInstanceId": "491ee058-f5bb-41ed-bcef-5dbf2ad79138",
  "success": true,
  "timeStamp": "2023-05-18T22:58:22.917351+02:00",
  "authType": "5G_AKA",
  "servingNetworkName": "5G:mnc070.mcc901.3gppnetwork.org"
}

end note

"AUSF" -> "AMF": 109, HTTP/2 200 rsp.

note right #D7FEFC
**AUSF to AMF**
end note

"AUSF" -> "AMF": 110, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AUSF to AMF**
10.0.4.1 to 10.0.3.1 (IPs)
HTTP/2 stream 3 payload
{
  "authResult": "AUTHENTICATION_SUCCESS",
  "supi": "imsi-901700000000004",
  "kseaf": "1ee24790f31e40c27eb59109320f80b4848e0fd6e59d2afaf4e036fac15e8de6"
}

end note

@enduml
