@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "AMF"
participant "SMF"
participant "UPF"
participant "UDM"
participant "NRF"
participant "PCF"

"SMF" -> "NRF": 1, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**SMF to NRF**
end note

"SMF" -> "NRF": 2, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**SMF to NRF**
end note

"NRF" -> "SMF": 4, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to SMF**
end note

"AMF" -> "SMF": 25, HTTP/2 req.\nPOST  /nsmf-pdusession/v1/sm-contexts/1/modify

note right #03B5AA
**AMF to SMF**
end note

"AMF" -> "SMF": 29, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to SMF**
end note

"SMF" -> "UPF": 32, PFCP req.\nPFCP Session Modification Request (52)

note right #03B5AA
**SMF to UPF**
end note

"UPF" -> "SMF": 33, PFCP rsp.\nPFCP Session Modification Response (53)

note right #D7FEFC
**UPF to SMF**
end note

"SMF" -> "AMF": 35, HTTP/2 200 rsp.

note right #D7FEFC
**SMF to AMF**
end note

"SMF" -> "AMF": 37, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**SMF to AMF**
end note

"AMF" -> "SMF": 46, HTTP/2 req.\nPOST  /nsmf-pdusession/v1/sm-contexts/1/release

note right #03B5AA
**AMF to SMF**
end note

"AMF" -> "SMF": 48, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to SMF**
end note

"SMF" -> "PCF": 60, HTTP/2 req.\nPOST  /npcf-smpolicycontrol/v1/sm-policies/1/delete

note right #03B5AA
**SMF to PCF**
end note

"SMF" -> "PCF": 62, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**SMF to PCF**
end note

"PCF" -> "SMF": 70, HTTP/2 204 rsp.

note right #D7FEFC
**PCF to SMF**
end note

"SMF" -> "UPF": 72, PFCP req.\nPFCP Session Deletion Request (54)

note right #03B5AA
**SMF to UPF**
end note

"UPF" -> "SMF": 73, PFCP rsp.\nPFCP Session Deletion Response (55)

note right #D7FEFC
**UPF to SMF**
end note

"SMF" -> "AMF": 74, HTTP/2 204 rsp.

note right #D7FEFC
**SMF to AMF**
end note

"AMF" -> "SMF": 76, HTTP/2 req.\nPOST  /nsmf-pdusession/v1/sm-contexts

note right #03B5AA
**AMF to SMF**
end note

"AMF" -> "SMF": 78, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to SMF**
end note

"SMF" -> "UDM": 94, HTTP/2 req.\nGET  /nudm-sdm/v2/imsi-901700000000004/sm-data

note right #03B5AA
**SMF to UDM**
end note

"UDM" -> "SMF": 97, HTTP/2 200 rsp.

note right #D7FEFC
**UDM to SMF**
end note

"UDM" -> "SMF": 98, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDM to SMF**
end note

"SMF" -> "AMF": 101, HTTP/2 201 rsp.

note right #D7FEFC
**SMF to AMF**
end note

"SMF" -> "PCF": 103, HTTP/2 req.\nPOST  /npcf-smpolicycontrol/v1/sm-policies

note right #03B5AA
**SMF to PCF**
end note

"SMF" -> "PCF": 104, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**SMF to PCF**
10.0.14.1 to 10.0.10.1 (IPs)
HTTP/2 stream 3 payload
{
  "supi": "imsi-901700000000004",
  "pduSessionId": 1,
  "pduSessionType": "IPV4",
  "dnn": "CustomSlice",
  "notificationUri": "http://10.0.14.1:7777/nsmf-callback/v1/sm-policy-notify/2",
  "ipv4Address": "10.45.0.3",
  "subsSessAmbr": {
    "uplink": "1048576 Kbps",
    "downlink": "1048576 Kbps"
  },
  "subsDefQos": {
    "5qi": 9,
    "arp": {
      "priorityLevel": 8,
      "preemptCap": "NOT_PREEMPT",
      "preemptVuln": "NOT_PREEMPTABLE"
    },
    "priorityLevel": 8
  },
  "sliceInfo": {
    "sst": 1,
    "sd": "000001"
  },
  "suppFeat": "4000000"
}

end note

"SMF" -> "AMF": 106, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**SMF to AMF**
end note

"PCF" -> "SMF": 108, HTTP/2 201 rsp.

note right #D7FEFC
**PCF to SMF**
end note

"PCF" -> "SMF": 109, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**PCF to SMF**
end note

"SMF" -> "UPF": 111, PFCP req.\nPFCP Session Establishment Request (50)

note right #03B5AA
**SMF to UPF**
end note

"UPF" -> "SMF": 113, PFCP rsp.\nPFCP Session Establishment Response (51)

note right #D7FEFC
**UPF to SMF**
end note

"SMF" -> "AMF": 126, HTTP/2 req.\nPOST  /namf-comm/v1/ue-contexts/imsi-901700000000004/n1-n2-messages

note right #03B5AA
**SMF to AMF**
end note

"SMF" -> "AMF": 128, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**SMF to AMF**
end note

"AMF" -> "SMF": 134, HTTP/2 200 rsp.

note right #D7FEFC
**AMF to SMF**
end note

"AMF" -> "SMF": 135, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to SMF**
end note

"AMF" -> "SMF": 137, HTTP/2 req.\nPOST  /nsmf-pdusession/v1/sm-contexts/2/modify

note right #03B5AA
**AMF to SMF**
end note

"AMF" -> "SMF": 139, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to SMF**
end note

"SMF" -> "UPF": 141, PFCP req.\nPFCP Session Modification Request (52)

note right #03B5AA
**SMF to UPF**
end note

"UPF" -> "SMF": 142, PFCP rsp.\nPFCP Session Modification Response (53)

note right #D7FEFC
**UPF to SMF**
end note

"SMF" -> "AMF": 143, HTTP/2 204 rsp.

note right #D7FEFC
**SMF to AMF**
end note

"SMF" -> "NRF": 145, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**SMF to NRF**
end note

"SMF" -> "NRF": 146, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**SMF to NRF**
end note

"NRF" -> "SMF": 148, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to SMF**
end note

"SMF" -> "NRF": 154, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**SMF to NRF**
end note

"SMF" -> "NRF": 155, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**SMF to NRF**
end note

"NRF" -> "SMF": 157, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to SMF**
end note

@enduml
