@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "AMF"
participant "AUSF"
participant "UDM"
participant "NRF"

"AUSF" -> "NRF": 1, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 2, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "AUSF": 4, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to AUSF**
end note

"AUSF" -> "NRF": 6, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 7, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "AUSF": 9, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"AUSF" -> "NRF": 11, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 12, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "AUSF": 14, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"AUSF" -> "NRF": 16, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 17, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "AUSF": 19, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"AUSF" -> "NRF": 21, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 22, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "AUSF": 24, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"AUSF" -> "NRF": 26, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 27, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "AUSF": 29, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"AUSF" -> "NRF": 31, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 32, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "AUSF": 34, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"AUSF" -> "NRF": 36, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 37, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "AUSF": 39, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"AUSF" -> "NRF": 41, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 42, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "AUSF": 44, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"AUSF" -> "NRF": 46, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 47, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "AUSF": 49, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"AMF" -> "AUSF": 60, HTTP/2 req.\nPOST  /nausf-auth/v1/ue-authentications

note right #03B5AA
**AMF to AUSF**
end note

"AMF" -> "AUSF": 62, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to AUSF**
end note

"AUSF" -> "NRF": 67, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "AUSF": 68, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"NRF" -> "AUSF": 70, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"AUSF" -> "UDM": 84, HTTP/2 req.\nPOST  /nudm-ueau/v1/suci-0-901-70-0000-0-0-0000000004/security-information/generate-auth-data

note right #03B5AA
**AUSF to UDM**
end note

"AUSF" -> "UDM": 88, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to UDM**
end note

"UDM" -> "AUSF": 91, HTTP/2 200 rsp.

note right #D7FEFC
**UDM to AUSF**
end note

"UDM" -> "AUSF": 92, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to AUSF**
end note

"AUSF" -> "AMF": 95, HTTP/2 201 rsp.

note right #D7FEFC
**AUSF to AMF**
end note

"AUSF" -> "AMF": 96, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to AMF**
end note

"AMF" -> "AUSF": 98, HTTP/2 req.\nPUT  /nausf-auth/v1/ue-authentications/1/5g-aka-confirmation

note right #03B5AA
**AMF to AUSF**
end note

"AMF" -> "AUSF": 100, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to AUSF**
end note

"AUSF" -> "UDM": 102, HTTP/2 req.\nPOST  /nudm-ueau/v1/imsi-901700000000004/auth-events

note right #03B5AA
**AUSF to UDM**
end note

"AUSF" -> "UDM": 104, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to UDM**
end note

"UDM" -> "AUSF": 106, HTTP/2 201 rsp.

note right #D7FEFC
**UDM to AUSF**
end note

"UDM" -> "AUSF": 107, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to AUSF**
end note

"AUSF" -> "AMF": 109, HTTP/2 200 rsp.

note right #D7FEFC
**AUSF to AMF**
end note

"AUSF" -> "AMF": 110, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to AMF**
end note

"AUSF" -> "NRF": 112, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 113, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "AUSF": 115, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"AUSF" -> "NRF": 117, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 118, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "AUSF": 120, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"AUSF" -> "NRF": 122, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 123, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "AUSF": 125, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"AUSF" -> "NRF": 127, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 128, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "AUSF": 130, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"AUSF" -> "NRF": 132, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 133, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "AUSF": 135, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"AUSF" -> "NRF": 137, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 138, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "AUSF": 140, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"AUSF" -> "NRF": 142, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 143, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "AUSF": 145, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

@enduml
