@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "Malicious_Actor"
participant "PCF"
participant "BSF"

"Malicious_Actor" -> "PCF": 11, HTTP/2 req.\nPOST  /npcf-smpolicycontrol/v1/sm-policies/15/delete

note right #FFC2D9
**Malicious_Actor to PCF**
end note

"PCF" -> "BSF": 13, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #FFEAC2
**PCF to BSF**
end note

"BSF" -> "PCF": 15, HTTP/2 204 rsp.

note right #D7FEFC
**BSF to PCF**
end note

"PCF" -> "Malicious_Actor": 17, HTTP/2 204 rsp.

note right #D7FEFC
**PCF to Malicious_Actor**
end note

@enduml
