@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "UE_1"
participant "UE_2"
participant "UE_3"
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "10.0.14.10"
participant "8.8.8.8"
participant "10.45.0.5"

"gNB" -> "UPF": 1377, GTP<ICMP> ping req.\n+22.974s (18:19:38.720.353)

note right #5C8001
**gNB to UPF**
end note

"10.45.0.5" -> "8.8.8.8": 1378, ICMP ping req.\n+22.975s (18:19:38.720.545)

note right #5C8001
**10.45.0.5 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 1379, ICMP ping req.\n+22.975s (18:19:38.720.562)

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 1380, ICMP ping rsp.\n+23.011s (18:19:38.757.125)

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "10.45.0.5": 1381, ICMP ping rsp.\n+23.011s (18:19:38.757.161)

note right #EDFEC2
**8.8.8.8 to 10.45.0.5**
end note

"UPF" -> "gNB": 1382, GTP<ICMP> ping rsp.\n+23.011s (18:19:38.757.268)

note right #EDFEC2
**UPF to gNB**
end note

"10.0.14.10" -> "UPF": 2031, PFCP req.\nPFCP Association Setup Request (5)\n+68.899s (18:20:24.645.216)

note right #FFC2D9
**10.0.14.10 to UPF**
end note

"10.0.14.10" -> "UPF": 2033, PFCP req.\nPFCP Session Deletion Request (54)\n+68.917s (18:20:24.663.295)

note right #FFC2D9
**10.0.14.10 to UPF**
end note

"10.0.14.10" -> "UPF": 2034, PFCP req.\nPFCP Session Deletion Request (54)\n+68.936s (18:20:24.682.249)

note right #FFC2D9
**10.0.14.10 to UPF**
end note

"10.0.14.10" -> "UPF": 2035, PFCP req.\nPFCP Session Deletion Request (54)\n+68.961s (18:20:24.706.853)

note right #FFC2D9
**10.0.14.10 to UPF**
end note

"10.0.14.10" -> "UPF": 2036, PFCP req.\nPFCP Session Deletion Request (54)\n+68.986s (18:20:24.731.61)

note right #FFC2D9
**10.0.14.10 to UPF**
end note

"10.0.14.10" -> "UPF": 2037, PFCP req.\nPFCP Association Setup Request (5)\n+68.990s (18:20:24.736.457)

note right #FFC2D9
**10.0.14.10 to UPF**
end note

"10.0.14.10" -> "UPF": 2038, PFCP req.\nPFCP Session Deletion Request (54)\n+69.004s (18:20:24.749.611)

note right #FFC2D9
**10.0.14.10 to UPF**
end note

"10.0.14.10" -> "UPF": 2039, PFCP req.\nPFCP Session Deletion Request (54)\n+69.016s (18:20:24.762.396)

note right #FFC2D9
**10.0.14.10 to UPF**
end note

"10.0.14.10" -> "UPF": 2040, PFCP req.\nPFCP Session Deletion Request (54)\n+69.036s (18:20:24.781.614)

note right #FFC2D9
**10.0.14.10 to UPF**
end note

"10.0.14.10" -> "UPF": 2041, PFCP req.\nPFCP Session Deletion Request (54)\n+69.049s (18:20:24.795.288)

note right #FFC2D9
**10.0.14.10 to UPF**
end note

"10.0.14.10" -> "UPF": 2042, PFCP req.\nPFCP Association Setup Request (5)\n+69.058s (18:20:24.804.079)

note right #FFC2D9
**10.0.14.10 to UPF**
end note

"10.0.14.10" -> "UPF": 2043, PFCP req.\nPFCP Session Deletion Request (54)\n+69.067s (18:20:24.812.955)

note right #FFC2D9
**10.0.14.10 to UPF**
end note

"10.0.14.10" -> "UPF": 2044, PFCP req.\nPFCP Session Deletion Request (54)\n+69.075s (18:20:24.820.891)

note right #FFC2D9
**10.0.14.10 to UPF**
end note

@enduml
