@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "Spoofed IPs 10.*.0.1"
participant "UE"
participant "gNB"
participant "SMF"
participant "UPF"

"gNB" -> "UPF": 164, GTP<ICMP> ping req.

note right #5C8001
**gNB to UPF**
end note

"UE" -> "8.8.8.8": 165, ICMP ping req.

note right #5C8001
**UE to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 166, ICMP ping req.

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 167, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE": 168, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UE**
end note

"UPF" -> "gNB": 169, GTP<ICMP> ping rsp.

note right #EDFEC2
**UPF to gNB**
end note
"Spoofed IPs 10.*.0.1" -> "UPF": 717, PFCP req.

note right #FFC2D9
**Spoofed IPs 10.*.0.1 to UPF**
end note

"UPF" -> "Spoofed IPs 10.*.0.1": 718, PFCP rsp.

note right #FFEAC2
**UPF to Spoofed IPs 10.*.0.1**
end note

"UPF" -> "SMF": 1110, PFCP req.\nPFCP Association Setup Request (5)

note right #03B5AA
**UPF to SMF**
end note

"SMF" -> "UPF": 1111, PFCP rsp.\nPFCP Association Setup Response (6)

note right #D7FEFC
**SMF to UPF**
end note

"gNB" -> "UPF": 1296, GTP<ICMP> ping req.

note right #5C8001
**gNB to UPF**
end note

@enduml





