@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "UE"
participant "gNB"
participant "SMF"
participant "UPF"
participant "Spoofed IPs 10.*.0.1"


"gNB" -> "UPF": 164, GTP<ICMP> ping req.\n+21.451s (16:1:23.602.934)

note right #5C8001
**gNB to UPF**
end note

"UE" -> "8.8.8.8": 165, ICMP ping req.\n+21.452s (16:1:23.604.018)

note right #5C8001
**UE to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 166, ICMP ping req.\n+21.452s (16:1:23.604.057)

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 167, ICMP ping rsp.\n+21.476s (16:1:23.627.574)

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE": 168, ICMP ping rsp.\n+21.476s (16:1:23.627.602)

note right #EDFEC2
**8.8.8.8 to UE**
end note

"UPF" -> "gNB": 169, GTP<ICMP> ping rsp.\n+21.476s (16:1:23.627.928)

note right #EDFEC2
**UPF to gNB**
end note
"Spoofed IPs 10.*.0.1" -> "UPF": 717, PFCP req.\nPFCP Association Setup Request (5)\n+78.542s (16:2:20.693.785)

note right #FFC2D9
**Spoofed IPs 10.*.0.1 to UPF**
end note

"UPF" -> "Spoofed IPs 10.*.0.1": 718, PFCP rsp.\nPFCP Association Setup Response (6)\n+78.547s (16:2:20.698.402)

note right #D7FEFC
**UPF to Spoofed IPs 10.*.0.1**
end note

"Spoofed IPs 10.*.0.1" -> "UPF": 719, PFCP req.\nPFCP Association Setup Request (5)\n+78.623s (16:2:20.774.568)

note right #FFC2D9
**Spoofed IPs 10.*.0.1 to UPF**
end note

"UPF" -> "Spoofed IPs 10.*.0.1": 720, PFCP rsp.\nPFCP Association Setup Response (6)\n+78.623s (16:2:20.774.86)

note right #D7FEFC
**UPF to Spoofed IPs 10.*.0.1**
end note

"Spoofed IPs 10.*.0.1" -> "UPF": 727, PFCP req.\nPFCP Association Setup Request (5)\n+78.907s (16:2:21.59.195)

note right #FFC2D9
**Spoofed IPs 10.*.0.1 to UPF**
end note

"gNB" -> "UPF": 1296, GTP<ICMP> ping req.\n+92.766s (16:2:34.918.138)

note right #5C8001
**gNB to UPF**
end note

"gNB" -> "UPF": 1304, GTP<ICMP> ping req.\n+93.786s (16:2:35.937.532)

note right #5C8001
**gNB to UPF**
end note

"gNB" -> "UPF": 1307, GTP<ICMP> ping req.\n+94.810s (16:2:36.961.556)

note right #5C8001
**gNB to UPF**
end note

@enduml





