@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "UE_1"
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "SGWU"
participant "SGWC"
participant "NRF"
participant "NSSF"
participant "BSF"
participant "PCF"
participant "AUSF"
participant "8.8.8.8"
participant "UDR"
participant "UDM"

"NRF" -> "NRF": 1511, HTTP/2 400 rsp.\n+9.296s (16:11:59.44.816)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 1512, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+9.296s (16:11:59.44.878)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1537, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/227253aa-8c42-41ed-805b-6d794761ecc2\n+9.475s (16:11:59.223.788)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1541, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+9.475s (16:11:59.223.879)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1544, HTTP/2 req.\nPOST  /nnrf-nfm/v1/nf-status-notify\n+9.475s (16:11:59.224.243)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1546, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+9.475s (16:11:59.224.274)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1548, HTTP/2 req.\nPOST  /nnrf-nfm/v1/nf-status-notify\n+9.475s (16:11:59.224.335)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1550, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+9.475s (16:11:59.224.363)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1552, HTTP/2 201 rsp.\n+9.476s (16:11:59.224.481)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 1553, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+9.476s (16:11:59.224.748)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1554, HTTP/2 400 rsp.\n+9.476s (16:11:59.224.783)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 1555, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+9.476s (16:11:59.224.795)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1556, HTTP/2 400 rsp.\n+9.476s (16:11:59.224.826)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 1557, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+9.476s (16:11:59.224.835)

note right #03B5AA
**NRF to NRF**
end note

"UPF" -> "NRF": 1597, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/1aece6f4-8c42-41ed-9a79-a36ccde6a2bf\n+10.018s (16:11:59.766.911)

note right #03B5AA
**UPF to NRF**
end note

"UPF" -> "NRF": 1598, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+10.018s (16:11:59.767.093)

note right #03B5AA
**UPF to NRF**
end note

"NRF" -> "UPF": 1600, HTTP/2 204 rsp.\n+10.019s (16:11:59.767.78)

note right #D7FEFC
**NRF to UPF**
end note

"UPF" -> "NRF": 1601, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/1afe2428-8c42-41ed-8ba6-5b3879039535\n+10.032s (16:11:59.780.969)

note right #03B5AA
**UPF to NRF**
end note

"UPF" -> "NRF": 1603, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+10.032s (16:11:59.781.305)

note right #03B5AA
**UPF to NRF**
end note

"NRF" -> "UPF": 1605, HTTP/2 204 rsp.\n+10.033s (16:11:59.781.853)

note right #D7FEFC
**NRF to UPF**
end note

"UPF" -> "NRF": 1608, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/1b01a760-8c42-41ed-92ed-fd2c3ba87b29\n+10.064s (16:11:59.813.354)

note right #03B5AA
**UPF to NRF**
end note

"UPF" -> "NRF": 1609, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+10.065s (16:11:59.813.494)

note right #03B5AA
**UPF to NRF**
end note

"NRF" -> "UPF": 1611, HTTP/2 204 rsp.\n+10.065s (16:11:59.814.041)

note right #D7FEFC
**NRF to UPF**
end note

"SGWC" -> "SGWU": 1691, PFCP req.\nPFCP Association Setup Request (5)\n+11.308s (16:12:1.56.51)

note right #03B5AA
**SGWC to SGWU**
end note

"SGWU" -> "SGWC": 1692, PFCP rsp.\nPFCP Association Setup Response (6)\n+11.308s (16:12:1.56.627)

note right #D7FEFC
**SGWU to SGWC**
end note

"UPF" -> "NRF": 1693, HTTP/2 req.\nDELETE  /nnrf-nfm/v1/nf-instances/1b01a760-8c42-41ed-92ed-fd2c3ba87b29\n+11.322s (16:12:1.70.521)

note right #03B5AA
**UPF to NRF**
end note

"NRF" -> "UPF": 1694, HTTP/2 204 rsp.\n+11.323s (16:12:1.71.706)

note right #D7FEFC
**NRF to UPF**
end note

"NRF" -> "NRF": 1696, HTTP/2 req.\nPOST  /nnrf-nfm/v1/nf-status-notify\n+11.323s (16:12:1.71.81)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1697, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+11.323s (16:12:1.71.841)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1699, HTTP/2 400 rsp.\n+11.323s (16:12:1.71.989)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 1700, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+11.323s (16:12:1.72.011)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1717, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/23a0d4cc-8c42-41ed-bf08-4305d2ff916b\n+11.473s (16:12:1.221.642)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1722, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+11.481s (16:12:1.229.51)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1725, HTTP/2 req.\nPOST  /nnrf-nfm/v1/nf-status-notify\n+11.481s (16:12:1.230.043)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1726, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+11.481s (16:12:1.230.066)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1727, HTTP/2 201 rsp.\n+11.481s (16:12:1.230.091)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 1729, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+11.481s (16:12:1.230.242)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1730, HTTP/2 400 rsp.\n+11.481s (16:12:1.230.28)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 1731, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+11.481s (16:12:1.230.294)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1738, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions\n+11.681s (16:12:1.429.518)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1741, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+11.706s (16:12:1.454.504)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1743, HTTP/2 201 rsp.\n+11.706s (16:12:1.454.75)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 1744, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions\n+11.718s (16:12:1.466.434)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1745, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+11.718s (16:12:1.466.492)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1746, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions\n+11.718s (16:12:1.466.549)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1747, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+11.718s (16:12:1.466.603)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1748, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions\n+11.718s (16:12:1.466.647)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1749, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+11.718s (16:12:1.466.665)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1750, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions\n+11.718s (16:12:1.466.704)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1751, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+11.718s (16:12:1.466.721)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1752, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions\n+11.718s (16:12:1.466.757)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1753, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+11.718s (16:12:1.466.773)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1756, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+11.733s (16:12:1.482.004)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1757, HTTP/2 201 rsp.\n+11.733s (16:12:1.482.265)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 1758, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+11.733s (16:12:1.482.283)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1759, HTTP/2 201 rsp.\n+11.733s (16:12:1.482.352)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 1760, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+11.733s (16:12:1.482.366)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1761, HTTP/2 201 rsp.\n+11.734s (16:12:1.482.545)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 1762, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+11.734s (16:12:1.482.564)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1763, HTTP/2 201 rsp.\n+11.734s (16:12:1.482.635)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 1764, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+11.734s (16:12:1.482.65)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1765, HTTP/2 201 rsp.\n+11.734s (16:12:1.482.72)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 1767, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+11.734s (16:12:1.482.858)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1781, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/1de03582-8c42-41ed-86c5-cd08fab1e8b4\n+11.833s (16:12:1.581.981)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1782, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+11.833s (16:12:1.582.021)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1784, HTTP/2 204 rsp.\n+11.833s (16:12:1.582.186)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 1952, HTTP/2 req.\nDELETE  /nnrf-nfm/v1/nf-instances/20782a98-8c42-41ed-9dfa-d537dfca911c\n+12.732s (16:12:2.481.427)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1958, HTTP/2 404 rsp.\n+12.734s (16:12:2.482.751)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 1960, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+12.734s (16:12:2.482.774)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1988, HTTP/2 req.\nDELETE  /nnrf-nfm/v1/nf-instances/1aece6f4-8c42-41ed-9a79-a36ccde6a2bf\n+12.952s (16:12:2.700.651)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 1994, HTTP/2 404 rsp.\n+12.952s (16:12:2.700.972)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 1996, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+12.952s (16:12:2.700.994)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2012, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/1e96b370-8c42-41ed-a26b-99a4952fdbea\n+13.024s (16:12:2.772.734)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2014, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+13.024s (16:12:2.772.838)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2020, HTTP/2 404 rsp.\n+13.024s (16:12:2.773.195)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 2022, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+13.024s (16:12:2.773.377)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2038, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/24944238-8c42-41ed-9898-098bb83ac6cd\n+13.048s (16:12:2.796.891)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2042, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+13.052s (16:12:2.800.481)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2045, HTTP/2 201 rsp.\n+13.052s (16:12:2.801.426)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 2046, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+13.053s (16:12:2.801.455)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2048, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions\n+13.053s (16:12:2.802.35)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2049, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+13.054s (16:12:2.802.438)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2051, HTTP/2 201 rsp.\n+13.054s (16:12:2.803.295)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 2052, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+13.054s (16:12:2.803.324)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2068, HTTP/2 req.\nDELETE  /nnrf-nfm/v1/nf-instances/224c826a-8c42-41ed-bfe0-13f6e30cb1d5\n+13.074s (16:12:2.822.752)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2074, HTTP/2 404 rsp.\n+13.074s (16:12:2.823.102)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 2076, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+13.074s (16:12:2.823.125)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2100, HTTP/2 req.\nDELETE  /nnrf-nfm/v1/nf-instances/1de03582-8c42-41ed-86c5-cd08fab1e8b4\n+13.189s (16:12:2.937.513)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2106, HTTP/2 404 rsp.\n+13.189s (16:12:2.937.986)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 2108, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+13.189s (16:12:2.938.014)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2122, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/24a8d18a-8c42-41ed-9d6b-0713a676495c\n+13.198s (16:12:2.946.983)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2126, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+13.198s (16:12:2.947.077)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2138, HTTP/2 req.\nPOST  /nnrf-nfm/v1/nf-status-notify\n+13.199s (16:12:2.947.555)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2140, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+13.199s (16:12:2.947.576)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2142, HTTP/2 201 rsp.\n+13.199s (16:12:2.947.603)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 2143, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+13.199s (16:12:2.947.662)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2149, HTTP/2 400 rsp.\n+13.199s (16:12:2.947.989)

note right #D7FEFC
**NRF to NRF**
end note

"NRF" -> "NRF": 2150, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+13.199s (16:12:2.948.012)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2153, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions\n+13.204s (16:12:2.953.073)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 2154, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+13.205s (16:12:2.953.994)

note right #03B5AA
**NRF to NRF**
end note

@enduml
