@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "UE_1"
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "SGWU"
participant "SGWC"
participant "NRF"
participant "127.0.0.2"
participant "NSSF"
participant "127.0.0.8"
participant "127.0.0.4"
participant "AUSF"
participant "UDR"
participant "BSF"
participant "PCF"
participant "8.8.8.8"
participant "UDM"
participant "127.0.0.9"

"NRF" -> "NRF": 2552, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.072s (16:12:12.821.283)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2554, HTTP/2 204 rsp.\n+23.073s (16:12:12.821.479)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2571, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/24a8d18a-8c42-41ed-9d6b-0713a676495c\n+23.226s (16:12:12.975.13)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2572, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.226s (16:12:12.975.165)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2574, HTTP/2 204 rsp.\n+23.226s (16:12:12.975.303)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2605, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/23a0d4cc-8c42-41ed-bf08-4305d2ff916b\n+23.577s (16:12:13.326.216)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2606, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.577s (16:12:13.326.354)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2608, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/24ddd434-8c42-41ed-90dc-490cfe057891\n+23.578s (16:12:13.327.099)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2609, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.578s (16:12:13.327.133)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2610, HTTP/2 201 rsp.\n+23.583s (16:12:13.332.253)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2612, HTTP/2 req.\nPOST  /nnrf-nfm/v1/nf-status-notify\n+23.584s (16:12:13.332.582)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2613, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.584s (16:12:13.332.604)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2614, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.584s (16:12:13.332.679)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2615, HTTP/2 204 rsp.\n+23.584s (16:12:13.332.719)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2617, HTTP/2 400 rsp.\n+23.584s (16:12:13.332.915)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2618, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.584s (16:12:13.332.935)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2621, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions\n+23.586s (16:12:13.335.294)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2622, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.586s (16:12:13.335.324)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2623, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions\n+23.587s (16:12:13.335.44)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2624, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.587s (16:12:13.335.455)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2625, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions\n+23.587s (16:12:13.335.497)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2626, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.587s (16:12:13.335.509)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2627, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions\n+23.587s (16:12:13.335.539)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2628, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.587s (16:12:13.335.556)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2629, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions\n+23.587s (16:12:13.335.592)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2630, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.587s (16:12:13.335.603)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2632, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions\n+23.587s (16:12:13.335.701)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2633, HTTP/2 201 rsp.\n+23.595s (16:12:13.343.634)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2634, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.595s (16:12:13.343.715)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2635, HTTP/2 201 rsp.\n+23.595s (16:12:13.343.789)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2636, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.595s (16:12:13.343.803)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2637, HTTP/2 201 rsp.\n+23.595s (16:12:13.343.871)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2638, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.595s (16:12:13.343.885)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2639, HTTP/2 201 rsp.\n+23.595s (16:12:13.343.953)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2640, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.595s (16:12:13.343.967)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2641, HTTP/2 201 rsp.\n+23.595s (16:12:13.344.038)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2642, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.595s (16:12:13.344.053)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2644, HTTP/2 201 rsp.\n+23.595s (16:12:13.344.392)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2647, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/24e9b6e6-8c42-41ed-99a9-194d71752aec\n+23.626s (16:12:13.375.387)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2648, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.627s (16:12:13.375.444)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2650, HTTP/2 204 rsp.\n+23.627s (16:12:13.375.621)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2656, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/24eff830-8c42-41ed-8ebb-33a10a6f764e\n+23.658s (16:12:13.406.526)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2657, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.658s (16:12:13.406.58)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2659, HTTP/2 204 rsp.\n+23.658s (16:12:13.406.719)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2664, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/24988348-8c42-41ed-8d27-598d027c90ee\n+23.689s (16:12:13.437.988)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2665, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.689s (16:12:13.438.025)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2667, HTTP/2 204 rsp.\n+23.689s (16:12:13.438.302)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2680, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/25047cba-8c42-41ed-af13-379882efa776\n+23.800s (16:12:13.549.196)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2681, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.800s (16:12:13.549.221)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2683, HTTP/2 204 rsp.\n+23.800s (16:12:13.549.43)

note right #e6e6e6
**NRF to NRF**
end note

"SGWC" -> "SGWU": 2858, PFCP req.\nPFCP Association Setup Request (5)\n+29.830s (16:12:19.578.97)

note right #03B5AA
**SGWC to SGWU**
end note

"SGWU" -> "SGWC": 2859, PFCP rsp.\nPFCP Association Setup Response (6)\n+29.830s (16:12:19.579.122)

note right #D7FEFC
**SGWU to SGWC**
end note

"NRF" -> "NRF": 2874, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/24944238-8c42-41ed-9898-098bb83ac6cd\n+33.080s (16:12:22.828.648)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2875, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+33.080s (16:12:22.828.753)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2877, HTTP/2 204 rsp.\n+33.083s (16:12:22.832.048)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2879, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/24a8d18a-8c42-41ed-9d6b-0713a676495c\n+33.237s (16:12:22.986.012)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2880, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+33.237s (16:12:22.986.053)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2882, HTTP/2 204 rsp.\n+33.237s (16:12:22.986.288)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2888, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/24ddd434-8c42-41ed-90dc-490cfe057891\n+33.588s (16:12:23.337.118)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2889, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+33.588s (16:12:23.337.151)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2891, HTTP/2 204 rsp.\n+33.588s (16:12:23.337.361)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2893, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/23a0d4cc-8c42-41ed-bf08-4305d2ff916b\n+33.592s (16:12:23.340.572)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2894, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+33.592s (16:12:23.340.622)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2896, HTTP/2 204 rsp.\n+33.592s (16:12:23.340.78)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2898, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/24e9b6e6-8c42-41ed-99a9-194d71752aec\n+33.636s (16:12:23.384.538)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2899, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+33.636s (16:12:23.384.572)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2901, HTTP/2 204 rsp.\n+33.636s (16:12:23.384.809)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2903, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/24eff830-8c42-41ed-8ebb-33a10a6f764e\n+33.668s (16:12:23.416.831)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2904, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+33.668s (16:12:23.416.869)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2906, HTTP/2 204 rsp.\n+33.668s (16:12:23.417.157)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2908, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/24988348-8c42-41ed-8d27-598d027c90ee\n+33.691s (16:12:23.440.289)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2909, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+33.691s (16:12:23.440.34)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2911, HTTP/2 204 rsp.\n+33.692s (16:12:23.441.003)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 2914, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/25047cba-8c42-41ed-af13-379882efa776\n+33.808s (16:12:23.556.491)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2915, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+33.808s (16:12:23.556.523)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 2917, HTTP/2 204 rsp.\n+33.808s (16:12:23.556.658)

note right #e6e6e6
**NRF to NRF**
end note

"127.0.0.2" -> "127.0.0.8": 3136, \n+41.354s (16:12:31.102.906)

note right
**127.0.0.2 to 127.0.0.8**
end note

"127.0.0.8" -> "127.0.0.2": 3137, \n+41.382s (16:12:31.130.735)

note right
**127.0.0.8 to 127.0.0.2**
end note

"NRF" -> "NRF": 3253, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/24944238-8c42-41ed-9898-098bb83ac6cd\n+43.090s (16:12:32.839.375)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3254, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+43.091s (16:12:32.839.735)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3256, HTTP/2 204 rsp.\n+43.091s (16:12:32.839.838)

note right #e6e6e6
**NRF to NRF**
end note

"127.0.0.9" -> "127.0.0.4": 3261, \n+43.129s (16:12:32.877.746)

note right
**127.0.0.9 to 127.0.0.4**
end note

"127.0.0.4" -> "127.0.0.9": 3262, \n+43.134s (16:12:32.882.695)

note right
**127.0.0.4 to 127.0.0.9**
end note

"NRF" -> "NRF": 3264, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/24a8d18a-8c42-41ed-9d6b-0713a676495c\n+43.249s (16:12:32.998.182)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3265, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+43.249s (16:12:32.998.219)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3267, HTTP/2 204 rsp.\n+43.249s (16:12:32.998.358)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 3278, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/24ddd434-8c42-41ed-90dc-490cfe057891\n+43.596s (16:12:33.345.233)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3279, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+43.596s (16:12:33.345.257)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3281, HTTP/2 204 rsp.\n+43.597s (16:12:33.345.634)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 3283, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/23a0d4cc-8c42-41ed-bf08-4305d2ff916b\n+43.605s (16:12:33.354.412)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3284, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+43.606s (16:12:33.354.463)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3286, HTTP/2 204 rsp.\n+43.606s (16:12:33.355.048)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 3288, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/24e9b6e6-8c42-41ed-99a9-194d71752aec\n+43.650s (16:12:33.398.63)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3289, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+43.650s (16:12:33.398.729)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3291, HTTP/2 204 rsp.\n+43.650s (16:12:33.399.199)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 3293, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/24eff830-8c42-41ed-8ebb-33a10a6f764e\n+43.676s (16:12:33.424.738)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3294, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+43.676s (16:12:33.424.791)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3296, HTTP/2 204 rsp.\n+43.676s (16:12:33.425.009)

note right #e6e6e6
**NRF to NRF**
end note

"NRF" -> "NRF": 3298, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/24988348-8c42-41ed-8d27-598d027c90ee\n+43.697s (16:12:33.445.827)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3299, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+43.697s (16:12:33.445.902)

note right #b3b3b3
**NRF to NRF**
end note

@enduml
