@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "Lock"
participant "Lock_Picker"
participant "gNB"
participant "UPF"
participant "Lock_Server"

"gNB" -> "UPF": 172, GTP<KEY>\nAccess Request
note right #5C8001
**gNB to UPF**
end note

"Lock" -> "Lock_Server": 173, KEY\nAccess Request
note right #EDFEC2
**Lock to Lock_Server**
<User_ID>:<Password>
end note

"UPF" -> "Lock_Server": 173, KEY\nAccess Request
note right #EDFEC2
**UPF to Lock_Server**
end note

"Lock_Server" -> "UPF": 174, KEY\nAccess Denied
note right #5C8001
**Lock_Server to UPF**
end note

"Lock_Server" -> "Lock": 174, KEY\nAccess Denied
note right #5C8001
**Lock_Server to Lock**
end note

"UPF" -> "gNB": 175, GTP<KEY>\nAccess Denied

note right #EDFEC2
**UPF to gNB**
end note


"gNB" -> "UPF": 269, GTP<PFCP req.>\nPFCP Association Setup Request (5)
note right #5C8001
**gNB to UPF**
end note

"Lock_Picker" -> "UPF": 268, PFCP req.\nPFCP Association Setup Request (5)

note right #FFC2D9
**Lock_Picker to UPF**
end note

"UPF" -> "Lock_Picker": 272, PFCP rsp.\nPFCP Association Setup Response (6)

note right #FFEAC2
**UPF to Lock_Picker**
end note

"UPF" -> "gNB": 273, GTP<PFCP rsp.>\nPFCP Association Setup Response (6)

note right #EDFEC2
**UPF to gNB**
end note


"gNB" -> "UPF": 274,  GTP<PFCP req.>\nPFCP Session Modification Request (52)

note right #5C8001
**gNB to UPF**
end note

"Lock_Picker" -> "UPF": 275,  PFCP req.\nPFCP Session Modification Request (52)

note right #FFC2D9
**Lock_Picker to UPF**
<Lock_SEID> gNB IP: <Lock_Picker_IP>
end note

"UPF" -> "Lock_Picker": 277, PFCP rsp.\nPFCP Session Modification Response (53)

note right #FFEAC2
**UPF to Lock_Picker**
Accept
end note

"UPF" -> "gNB": 278, GTP<PFCP rsp.>\nPFCP Session Modification Response (53)

note right #EDFEC2
**UPF to gNB**
end note


"gNB" -> "UPF": 355, GTP<KEY>\nAccess Request
note right #5C8001
**gNB to UPF**
end note

"Lock" -> "Lock_Server": 356, KEY\nAccess Request
note right #EDFEC2
**Lock to Lock_Server**
<User_ID>:<Password>
end note

"UPF" -> "Lock_Server": 357, KEY\nAccess Request
note right #EDFEC2
**UPF to Lock_Server**
end note

"Lock_Server" -> "UPF": 358, KEY\nAccess Denied
note right #5C8001
**Lock_Server to UPF**
end note

"UPF" -> "Lock_Picker": 359, GTP<KEY>\nAccess Denied

note right #EDFEC2
**UPF to Lock_Picker**
end note

"UPF" -> "gNB": 360, GTP<GTP<KEY>>\nAccess Denied

note right #EDFEC2
**UPF to gNB**
end note


"gNB" -> "UPF": 371,  GTP<PFCP req.>\nPFCP Session Modification Request (52)

note right #5C8001
**gNB to UPF**
end note

"Lock_Picker" -> "UPF": 372,  PFCP req.\nPFCP Session Modification Request (52)

note right #FFC2D9
**Lock_Picker to UPF**
<Lock_SEID> gNB IP: <gNb_IP>
end note

"UPF" -> "Lock_Picker": 373, PFCP rsp.\nPFCP Session Modification Response (53)

note right #FFEAC2
**UPF to Lock_Picker**
Accept
end note

"UPF" -> "gNB": 374, GTP<PFCP rsp.>\nPFCP Session Modification Response (53)

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 172, GTP<KEY>\nAccess Granted
note right #5C8001
**gNB to UPF**
end note

"Lock_Picker" -> "Lock": 173, KEY\nAccess Granted
note right #EDFEC2
**Lock_Picker to Lock**
<User_ID>:<Password>
end note

"UPF" -> "Lock": 173, KEY\nAccess Granted
note right #EDFEC2
**UPF to Lock**
end note

"UPF" -> "gNB": 374, GTP<KEY>\nAccess Granted

note right #EDFEC2
**UPF to gNB**
end note
@enduml
