@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "UE_1"
participant "UE_0"
participant "UE_2"
participant "UE_3"
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "8.8.8.8"
participant "AUSF"
participant "UDR"
participant "10.0.14.10"
participant "UDM"
participant "BSF"
participant "NRF"
participant "PCF"

"UPF" -> "8.8.8.8": 959, ICMP ping req.\n+21.666s (19:38:8.738.542)

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 960, ICMP ping rsp.\n+21.726s (19:38:8.798.572)

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_1": 961, ICMP ping rsp.\n+21.726s (19:38:8.798.615)

note right #EDFEC2
**8.8.8.8 to UE_1**
end note

"UPF" -> "gNB": 962, GTP<ICMP> ping rsp.\n+21.726s (19:38:8.798.94)

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 963, GTP<ICMP> ping req.\n+22.662s (19:38:9.735.004)

note right #5C8001
**gNB to UPF**
end note

"UE_1" -> "8.8.8.8": 964, ICMP ping req.\n+22.662s (19:38:9.735.11)

note right #5C8001
**UE_1 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 965, ICMP ping req.\n+22.662s (19:38:9.735.124)

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 966, ICMP ping rsp.\n+22.683s (19:38:9.755.939)

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_1": 967, ICMP ping rsp.\n+22.683s (19:38:9.755.987)

note right #EDFEC2
**8.8.8.8 to UE_1**
end note

"UPF" -> "gNB": 968, GTP<ICMP> ping rsp.\n+22.683s (19:38:9.756.196)

note right #EDFEC2
**UPF to gNB**
end note

"NRF" -> "NRF": 969, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.012s (19:38:10.85.258)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 970, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.012s (19:38:10.85.347)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 972, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.013s (19:38:10.85.694)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 974, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.076s (19:38:10.149.192)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 975, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.076s (19:38:10.149.226)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 977, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.076s (19:38:10.149.368)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 979, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.116s (19:38:10.189.32)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 980, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.116s (19:38:10.189.359)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 982, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.117s (19:38:10.189.534)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 984, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.166s (19:38:10.238.959)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 985, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.166s (19:38:10.239.019)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 987, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.167s (19:38:10.239.664)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 989, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.288s (19:38:10.361.33)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 990, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.289s (19:38:10.361.394)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 992, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.289s (19:38:10.361.549)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 994, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.369s (19:38:10.441.478)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 995, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.369s (19:38:10.441.522)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 997, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.369s (19:38:10.441.708)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 999, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.422s (19:38:10.494.913)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1000, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.424s (19:38:10.496.52)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1002, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.424s (19:38:10.496.778)

note right #b3b3b3
**NRF to NRF**
end note

"gNB" -> "UPF": 1004, GTP<ICMP> ping req.\n+23.663s (19:38:10.736.092)

note right #5C8001
**gNB to UPF**
end note

"UE_1" -> "8.8.8.8": 1005, ICMP ping req.\n+23.663s (19:38:10.736.195)

note right #5C8001
**UE_1 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 1006, ICMP ping req.\n+23.663s (19:38:10.736.212)

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 1007, ICMP ping rsp.\n+23.718s (19:38:10.791.301)

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_1": 1008, ICMP ping rsp.\n+23.718s (19:38:10.791.34)

note right #EDFEC2
**8.8.8.8 to UE_1**
end note

"UPF" -> "gNB": 1009, GTP<ICMP> ping rsp.\n+23.719s (19:38:10.791.483)

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 1010, GTP<ICMP> ping req.\n+23.728s (19:38:10.800.597)

note right #5C8001
**gNB to UPF**
end note

"UE_2" -> "8.8.8.8": 1011, ICMP ping req.\n+23.728s (19:38:10.800.683)

note right #5C8001
**UE_2 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 1012, ICMP ping req.\n+23.728s (19:38:10.800.704)

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 1013, ICMP ping rsp.\n+23.751s (19:38:10.823.577)

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_2": 1014, ICMP ping rsp.\n+23.751s (19:38:10.823.616)

note right #EDFEC2
**8.8.8.8 to UE_2**
end note

"UPF" -> "gNB": 1015, GTP<ICMP> ping rsp.\n+23.751s (19:38:10.823.948)

note right #EDFEC2
**UPF to gNB**
end note

"NRF" -> "NRF": 1016, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.772s (19:38:10.845.197)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1017, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.772s (19:38:10.845.237)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1019, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+23.773s (19:38:10.845.407)

note right #b3b3b3
**NRF to NRF**
end note

"gNB" -> "UPF": 1028, GTP<ICMP> ping req.\n+24.730s (19:38:11.802.403)

note right #5C8001
**gNB to UPF**
end note

"UE_2" -> "8.8.8.8": 1029, ICMP ping req.\n+24.730s (19:38:11.802.5)

note right #5C8001
**UE_2 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 1030, ICMP ping req.\n+24.730s (19:38:11.802.515)

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 1031, ICMP ping rsp.\n+24.755s (19:38:11.827.423)

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_2": 1032, ICMP ping rsp.\n+24.755s (19:38:11.827.449)

note right #EDFEC2
**8.8.8.8 to UE_2**
end note

"UPF" -> "gNB": 1033, GTP<ICMP> ping rsp.\n+24.755s (19:38:11.827.533)

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 1042, GTP<ICMP> ping req.\n+25.730s (19:38:12.802.734)

note right #5C8001
**gNB to UPF**
end note

"UE_2" -> "8.8.8.8": 1043, ICMP ping req.\n+25.730s (19:38:12.803.009)

note right #5C8001
**UE_2 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 1044, ICMP ping req.\n+25.730s (19:38:12.803.036)

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 1045, ICMP ping rsp.\n+25.753s (19:38:12.825.445)

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_2": 1046, ICMP ping rsp.\n+25.753s (19:38:12.825.472)

note right #EDFEC2
**8.8.8.8 to UE_2**
end note

"UPF" -> "gNB": 1047, GTP<ICMP> ping rsp.\n+25.753s (19:38:12.825.559)

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 1054, GTP<ICMP> ping req.\n+26.731s (19:38:13.804.107)

note right #5C8001
**gNB to UPF**
end note

"UE_2" -> "8.8.8.8": 1055, ICMP ping req.\n+26.731s (19:38:13.804.372)

note right #5C8001
**UE_2 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 1056, ICMP ping req.\n+26.732s (19:38:13.804.399)

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 1057, ICMP ping rsp.\n+26.752s (19:38:13.824.552)

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_2": 1058, ICMP ping rsp.\n+26.752s (19:38:13.824.67)

note right #EDFEC2
**8.8.8.8 to UE_2**
end note

"UPF" -> "gNB": 1059, GTP<ICMP> ping rsp.\n+26.752s (19:38:13.825.104)

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 1062, GTP<ICMP> ping req.\n+27.732s (19:38:14.805.201)

note right #5C8001
**gNB to UPF**
end note

"UE_2" -> "8.8.8.8": 1063, ICMP ping req.\n+27.732s (19:38:14.805.315)

note right #5C8001
**UE_2 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 1064, ICMP ping req.\n+27.732s (19:38:14.805.367)

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 1065, ICMP ping rsp.\n+27.753s (19:38:14.825.653)

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_2": 1066, ICMP ping rsp.\n+27.753s (19:38:14.825.697)

note right #EDFEC2
**8.8.8.8 to UE_2**
end note

"UPF" -> "gNB": 1067, GTP<ICMP> ping rsp.\n+27.753s (19:38:14.825.796)

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 1068, GTP<ICMP> ping req.\n+27.760s (19:38:14.832.595)

note right #5C8001
**gNB to UPF**
end note

"UE_3" -> "8.8.8.8": 1069, ICMP ping req.\n+27.760s (19:38:14.832.685)

note right #5C8001
**UE_3 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 1070, ICMP ping req.\n+27.760s (19:38:14.832.706)

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 1071, ICMP ping rsp.\n+27.780s (19:38:14.852.919)

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_3": 1072, ICMP ping rsp.\n+27.780s (19:38:14.853.008)

note right #EDFEC2
**8.8.8.8 to UE_3**
end note

"UPF" -> "gNB": 1073, GTP<ICMP> ping rsp.\n+27.780s (19:38:14.853.234)

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 1074, GTP<ICMP> ping req.\n+28.761s (19:38:15.834.221)

note right #5C8001
**gNB to UPF**
end note

"UE_3" -> "8.8.8.8": 1075, ICMP ping req.\n+28.761s (19:38:15.834.337)

note right #5C8001
**UE_3 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 1076, ICMP ping req.\n+28.761s (19:38:15.834.352)

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 1077, ICMP ping rsp.\n+28.790s (19:38:15.862.913)

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_3": 1078, ICMP ping rsp.\n+28.790s (19:38:15.862.941)

note right #EDFEC2
**8.8.8.8 to UE_3**
end note

"UPF" -> "gNB": 1079, GTP<ICMP> ping rsp.\n+28.790s (19:38:15.863.022)

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 1089, GTP<ICMP> ping req.\n+29.763s (19:38:16.835.891)

note right #5C8001
**gNB to UPF**
end note

"UE_3" -> "8.8.8.8": 1090, ICMP ping req.\n+29.763s (19:38:16.835.985)

note right #5C8001
**UE_3 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 1091, ICMP ping req.\n+29.763s (19:38:16.835.999)

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 1092, ICMP ping rsp.\n+29.779s (19:38:16.852.281)

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_3": 1093, ICMP ping rsp.\n+29.779s (19:38:16.852.311)

note right #EDFEC2
**8.8.8.8 to UE_3**
end note

"UPF" -> "gNB": 1094, GTP<ICMP> ping rsp.\n+29.780s (19:38:16.852.395)

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 1095, GTP<ICMP> ping req.\n+30.765s (19:38:17.837.496)

note right #5C8001
**gNB to UPF**
end note

"UE_3" -> "8.8.8.8": 1096, ICMP ping req.\n+30.765s (19:38:17.837.588)

note right #5C8001
**UE_3 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 1097, ICMP ping req.\n+30.765s (19:38:17.837.603)

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 1098, ICMP ping rsp.\n+30.791s (19:38:17.863.92)

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_3": 1099, ICMP ping rsp.\n+30.791s (19:38:17.863.945)

note right #EDFEC2
**8.8.8.8 to UE_3**
end note

"UPF" -> "gNB": 1100, GTP<ICMP> ping rsp.\n+30.791s (19:38:17.864.028)

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 1103, GTP<ICMP> ping req.\n+31.767s (19:38:18.839.636)

note right #5C8001
**gNB to UPF**
end note

"UE_3" -> "8.8.8.8": 1104, ICMP ping req.\n+31.767s (19:38:18.839.723)

note right #5C8001
**UE_3 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 1105, ICMP ping req.\n+31.767s (19:38:18.839.736)

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 1106, ICMP ping rsp.\n+31.794s (19:38:18.866.435)

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_3": 1107, ICMP ping rsp.\n+31.794s (19:38:18.866.461)

note right #EDFEC2
**8.8.8.8 to UE_3**
end note

"UPF" -> "gNB": 1108, GTP<ICMP> ping rsp.\n+31.794s (19:38:18.866.543)

note right #EDFEC2
**UPF to gNB**
end note

@enduml
