@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "SGWU"
participant "SGWC"
participant "NRF"
participant "BSF"
participant "UDM"
participant "NSSF"
participant "AUSF"
participant "8.8.8.8"
participant "PCF"
participant "UDR"

"NRF" -> "UDR": 2981, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDR**
end note

"NRF" -> "BSF": 2984, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to BSF**
end note

"NRF" -> "BSF": 2985, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to BSF**
end note

"NRF" -> "PCF": 2988, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to PCF**
end note

"NRF" -> "PCF": 2989, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to PCF**
end note

"NRF" -> "PCF": 2992, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "PCF": 2993, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"PCF" -> "NRF": 2996, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions\nPATCH  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 2997, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions\nPATCH  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 2998, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 2999, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 3000, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions\nPATCH  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 3001, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions\nPATCH  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**PCF to NRF**
end note

"NSSF" -> "NRF": 3002, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/3c1774e6-f5a8-41ed-ba4e-c32b10ea0d21\nPATCH  /nnrf-nfm/v1/nf-instances/3c1774e6-f5a8-41ed-ba4e-c32b10ea0d21

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 3003, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/3c1774e6-f5a8-41ed-ba4e-c32b10ea0d21\nPATCH  /nnrf-nfm/v1/nf-instances/3c1774e6-f5a8-41ed-ba4e-c32b10ea0d21

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 3004, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 3005, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NRF" -> "PCF": 3012, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "PCF": 3013, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "NSSF": 3014, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to NSSF**
end note

"NRF" -> "NSSF": 3015, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to NSSF**
end note

"NRF" -> "PCF": 3018, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "PCF": 3019, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "NSSF": 3022, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NSSF**
end note

"NRF" -> "NSSF": 3023, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NSSF**
end note

"NRF" -> "PCF": 3026, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "PCF": 3027, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "PCF": 3028, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "PCF": 3029, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

@enduml
