@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "UE_1"
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "SGWU"
participant "SGWC"
participant "NRF"
participant "NSSF"
participant "BSF"
participant "PCF"
participant "UDR"
participant "8.8.8.8"
participant "AUSF"
participant "UDM"

"AMF" -> "NRF": 971, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/3a52609e-f5a8-41ed-956c-a9071229793c

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 974, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to NRF**
end note

"AMF" -> "NRF": 975, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to NRF**
end note

"NRF" -> "AMF": 984, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 985, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 986, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 987, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note

"AMF" -> "NRF": 990, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 991, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 992, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to NRF**
end note

"AMF" -> "NRF": 993, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to NRF**
end note

"AMF" -> "NRF": 994, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 995, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 996, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to NRF**
end note

"AMF" -> "NRF": 997, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to NRF**
end note

"AMF" -> "NRF": 998, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 999, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 1000, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to NRF**
end note

"AMF" -> "NRF": 1001, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to NRF**
end note

"AMF" -> "NRF": 1002, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 1003, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 1004, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to NRF**
end note

"AMF" -> "NRF": 1005, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to NRF**
end note

"AMF" -> "NRF": 1006, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 1007, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 1008, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to NRF**
end note

"AMF" -> "NRF": 1009, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to NRF**
end note

"AMF" -> "NRF": 1012, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 1013, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**AMF to NRF**
end note

"NRF" -> "AMF": 1014, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1015, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1016, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1017, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1020, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1021, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1022, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1023, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1026, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1027, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1028, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1029, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1032, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1033, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1034, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1035, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1038, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1039, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1040, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1041, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1044, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1045, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1046, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1047, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note

"AUSF" -> "NRF": 1080, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/3b33a82e-f5a8-41ed-a7cf-ff7f762bc422

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 1081, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/3b33a82e-f5a8-41ed-a7cf-ff7f762bc422

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 1082, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AUSF to NRF**
end note

"AUSF" -> "NRF": 1083, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AUSF to NRF**
end note

"NRF" -> "AUSF": 1086, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to AUSF**
end note

"NRF" -> "AUSF": 1087, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to AUSF**
end note

"UDM" -> "NRF": 1094, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/3b55f82a-f5a8-41ed-a1f8-a1fff7d9ed8f

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 1095, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/3b55f82a-f5a8-41ed-a1f8-a1fff7d9ed8f\nPATCH  /nnrf-nfm/v1/nf-instances/3b55f82a-f5a8-41ed-a1f8-a1fff7d9ed8f

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 1096, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDM to NRF**
end note

"UDM" -> "NRF": 1097, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDM to NRF**
end note

"NRF" -> "UDM": 1100, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to UDM**
end note

"NRF" -> "UDM": 1101, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to UDM**
end note

"SMF" -> "UPF": 1104, PFCP req.\nPFCP Association Setup Request (5)

note right #03B5AA
**SMF to UPF**
end note

"SMF" -> "NRF": 1124, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/3a535a9e-f5a8-41ed-a2d6-e544d47350aa

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 1125, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/3a535a9e-f5a8-41ed-a2d6-e544d47350aa

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 1128, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**SMF to NRF**
end note

"SMF" -> "NRF": 1129, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**SMF to NRF**
end note

"UPF" -> "SMF": 1132, PFCP rsp.\nPFCP Association Setup Response (6)

note right #D7FEFC
**UPF to SMF**
end note

"UPF" -> "SMF": 1133, PFCP rsp.\nPFCP Association Setup Response (6)

note right #D7FEFC
**UPF to SMF**
end note

"NRF" -> "SMF": 1142, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to SMF**
end note

"NRF" -> "SMF": 1143, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to SMF**
end note

"NRF" -> "SMF": 1146, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to SMF**
end note

"NRF" -> "SMF": 1147, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to SMF**
end note

"SMF" -> "NRF": 1152, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 1153, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 1154, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**SMF to NRF**
end note

"SMF" -> "NRF": 1155, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**SMF to NRF**
end note

"SMF" -> "NRF": 1156, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 1157, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 1158, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**SMF to NRF**
end note

"SMF" -> "NRF": 1159, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**SMF to NRF**
end note

"SMF" -> "NRF": 1160, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 1161, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 1162, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**SMF to NRF**
end note

"SMF" -> "NRF": 1163, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**SMF to NRF**
end note

"NRF" -> "SMF": 1166, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to SMF**
end note

"NRF" -> "SMF": 1167, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to SMF**
end note

"NRF" -> "SMF": 1168, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to SMF**
end note

"NRF" -> "SMF": 1169, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to SMF**
end note

"NRF" -> "SMF": 1172, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to SMF**
end note

"NRF" -> "SMF": 1173, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to SMF**
end note

"NRF" -> "SMF": 1174, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to SMF**
end note

"NRF" -> "SMF": 1175, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to SMF**
end note

"NRF" -> "SMF": 1178, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to SMF**
end note

"NRF" -> "SMF": 1179, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to SMF**
end note

"NRF" -> "SMF": 1180, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to SMF**
end note

"NRF" -> "SMF": 1181, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to SMF**
end note

@enduml
