@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "UE_1"
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "SGWU"
participant "SGWC"
participant "AUSF"
participant "UDM"
participant "UDR"
participant "NRF"
participant "8.8.8.8"
participant "BSF"
participant "NSSF"
participant "PCF"


"gNB" -> "AMF": 1284, NGAP NGSetup (21)

note right #CDDCF3
**gNB to AMF**
end note

"AMF" -> "gNB": 1288, NGAP NGSetup (21)

note right #CDDCF3
**AMF to gNB**
end note

"gNB" -> "AMF": 1450, NGAP InitialUEMessage (15),\nNAS Registration request (0x41)

note right #285AA4
**gNB to AMF**
end note

"AMF" -> "NRF": 1452, HTTP/2 req.\nGET  /nnrf-disc/v1/nf-instances

note right #03B5AA
**AMF to NRF**
end note

"NRF" -> "AMF": 1454, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to AMF**
end note


"NRF" -> "AMF": 1456, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note


"AMF" -> "AUSF": 1478, HTTP/2 req.\nPOST  /nausf-auth/v1/ue-authentications

note right #03B5AA
**AMF to AUSF**
end note


"AMF" -> "AUSF": 1482, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to AUSF**
end note

"AUSF" -> "NRF": 1490, HTTP/2 req.\nGET  /nnrf-disc/v1/nf-instances

note right #03B5AA
**AUSF to NRF**
end note


"NRF" -> "AUSF": 1492, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to AUSF**
end note

"NRF" -> "AUSF": 1496, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AUSF**
end note

"AUSF" -> "UDM": 1524, HTTP/2 req.\nPOST  /nudm-ueau/v1/suci-0-901-70-0000-0-0-0000000004/security-information/generate-auth-data

note right #03B5AA
**AUSF to UDM**
end note

"AUSF" -> "UDM": 1532, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AUSF to UDM**
end note

"UDM" -> "NRF": 1536, HTTP/2 req.\nGET  /nnrf-disc/v1/nf-instances\nPATCH  /nnrf-disc/v1/nf-instances

note right #03B5AA
**UDM to NRF**
end note


"NRF" -> "UDM": 1538, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to UDM**
end note

"NRF" -> "UDM": 1542, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to UDM**
end note

"UDM" -> "UDR": 1570, HTTP/2 req.\nGET  /nudr-dr/v1/subscription-data/imsi-901700000000004/authentication-data/authentication-subscription

note right #03B5AA
**UDM to UDR**
end note

"UDR" -> "UDM": 1585, HTTP/2 200 rsp.

note right #D7FEFC
**UDR to UDM**
end note

"UDR" -> "UDM": 1587, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDR to UDM**
end note

"UDM" -> "AUSF": 1593, HTTP/2 200 rsp.

note right #D7FEFC
**UDM to AUSF**
end note

"UDM" -> "AUSF": 1595, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDM to AUSF**
end note

"AUSF" -> "AMF": 1601, HTTP/2 201 rsp.

note right #D7FEFC
**AUSF to AMF**
end note

"AUSF" -> "AMF": 1603, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AUSF to AMF**
end note

"AMF" -> "gNB": 1607, NGAP DownlinkNASTransport (4),\nNAS Authentication request (0x56)

note right #285AA4
**AMF to gNB**
end note

"gNB" -> "AMF": 1609, NGAP UplinkNASTransport (46),\nNAS Authentication response (0x57)

note right #CDDCF3
**gNB to AMF**
end note

"AMF" -> "AUSF": 1611, HTTP/2 req.\nPUT  /nausf-auth/v1/ue-authentications/1/5g-aka-confirmation

note right #03B5AA
**AMF to AUSF**
end note

"AMF" -> "AUSF": 1615, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to AUSF**
end note

"AUSF" -> "UDM": 1619, HTTP/2 req.\nPOST  /nudm-ueau/v1/imsi-901700000000004/auth-events

note right #03B5AA
**AUSF to UDM**
end note

"AUSF" -> "UDM": 1623, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AUSF to UDM**
end note

"UDM" -> "UDR": 1627, HTTP/2 req.\nPUT  /nudr-dr/v1/subscription-data/imsi-901700000000004/authentication-data/authentication-status

note right #03B5AA
**UDM to UDR**
end note

"UDM" -> "UDR": 1631, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDM to UDR**
end note

"UDR" -> "UDM": 1642, HTTP/2 204 rsp.

note right #D7FEFC
**UDR to UDM**
end note


"UDM" -> "AUSF": 1644, HTTP/2 201 rsp.

note right #D7FEFC
**UDM to AUSF**
end note


"UDM" -> "AUSF": 1646, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDM to AUSF**
end note


"AUSF" -> "AMF": 1650, HTTP/2 200 rsp.

note right #D7FEFC
**AUSF to AMF**
end note


"AUSF" -> "AMF": 1652, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AUSF to AMF**
end note

"AMF" -> "gNB": 1656, NGAP DownlinkNASTransport (4),\nNAS Security mode command (0x5d)

note right #CDDCF3
**AMF to gNB**
end note

"gNB" -> "AMF": 1658, NGAP UplinkNASTransport (46),\nNAS Security mode complete (0x5e),\nNAS Registration request (0x41)

note right #285AA4
**gNB to AMF**
end note

"AMF" -> "NRF": 1662, HTTP/2 req.\nGET  /nnrf-disc/v1/nf-instances

note right #03B5AA
**AMF to NRF**
end note

"NRF" -> "AMF": 1664, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1666, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note

"AMF" -> "UDM": 1688, HTTP/2 req.\nPUT  /nudm-uecm/v1/imsi-901700000000004/registrations/amf-3gpp-access

note right #03B5AA
**AMF to UDM**
end note

@enduml
