@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "UE_1"
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "SGWU"
participant "SGWC"
participant "NRF"
participant "UDR"
participant "8.8.8.8"
participant "BSF"
participant "NSSF"
participant "AUSF"
participant "PCF"
participant "UDM"

"SGWC" -> "SGWU": 301, PFCP req.\nPFCP Association Setup Request (5)

note right #03B5AA
**SGWC to SGWU**
end note

"SGWU" -> "SGWC": 303, PFCP,ICMP req.\nPFCP Association Setup Request (5)

note right #03B5AA
**SGWU to SGWC**
end note

"SMF" -> "UPF": 358, PFCP req.\nPFCP Association Setup Request (5)

note right #03B5AA
**SMF to UPF**
end note

"UPF" -> "SMF": 360, PFCP,ICMP req.\nPFCP Association Setup Request (5)

note right #03B5AA
**UPF to SMF**
end note

"AUSF" -> "NRF": 388, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/3b33a82e-f5a8-41ed-a7cf-ff7f762bc422

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 389, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/3b33a82e-f5a8-41ed-a7cf-ff7f762bc422

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 396, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AUSF to NRF**
end note

"AUSF" -> "NRF": 397, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AUSF to NRF**
end note

"NRF" -> "AUSF": 402, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to AUSF**
end note

"NRF" -> "AUSF": 403, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to AUSF**
end note

"NRF" -> "AUSF": 404, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AUSF**
end note

"NRF" -> "AUSF": 405, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AUSF**
end note

"NRF" -> "AUSF": 406, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AUSF**
end note

"NRF" -> "AUSF": 407, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AUSF**
end note

"AUSF" -> "NRF": 412, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 413, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 416, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AUSF to NRF**
end note

"AUSF" -> "NRF": 417, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AUSF to NRF**
end note

"NRF" -> "AUSF": 420, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to AUSF**
end note

"NRF" -> "AUSF": 421, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to AUSF**
end note

"NRF" -> "AUSF": 422, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AUSF**
end note

"NRF" -> "AUSF": 423, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AUSF**
end note

"UDM" -> "NRF": 458, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/3b55f82a-f5a8-41ed-a1f8-a1fff7d9ed8f

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 459, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/3b55f82a-f5a8-41ed-a1f8-a1fff7d9ed8f

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 466, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDM to NRF**
end note

"UDM" -> "NRF": 467, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDM to NRF**
end note

"NRF" -> "UDM": 472, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to UDM**
end note

"NRF" -> "UDM": 473, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to UDM**
end note

"NRF" -> "UDM": 474, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to UDM**
end note

"NRF" -> "UDM": 475, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to UDM**
end note

"UDM" -> "NRF": 476, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 477, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 478, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDM to NRF**
end note

"UDM" -> "NRF": 479, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDM to NRF**
end note

"NRF" -> "UDM": 482, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to UDM**
end note

"NRF" -> "UDM": 483, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to UDM**
end note

"NRF" -> "UDM": 484, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to UDM**
end note

"NRF" -> "UDM": 485, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to UDM**
end note

"SGWC" -> "SGWU": 488, PFCP req.\nPFCP Association Setup Request (5)

note right #03B5AA
**SGWC to SGWU**
end note

"SGWU" -> "SGWC": 490, PFCP rsp.\nPFCP Association Setup Response (6)

note right #D7FEFC
**SGWU to SGWC**
end note

"SGWU" -> "SGWC": 491, PFCP rsp.\nPFCP Association Setup Response (6)

note right #D7FEFC
**SGWU to SGWC**
end note

"PCF" -> "NRF": 540, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/3bda8e00-f5a8-41ed-8b25-8778ac8a932f

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 541, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/3bda8e00-f5a8-41ed-8b25-8778ac8a932f

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 548, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**PCF to NRF**
end note

"PCF" -> "NRF": 549, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**PCF to NRF**
end note

"NRF" -> "PCF": 554, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to PCF**
end note

"NRF" -> "PCF": 555, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to PCF**
end note

"NRF" -> "PCF": 556, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to PCF**
end note

"NRF" -> "PCF": 557, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to PCF**
end note

"PCF" -> "NRF": 560, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 561, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 562, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**PCF to NRF**
end note

"PCF" -> "NRF": 563, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**PCF to NRF**
end note

"NRF" -> "PCF": 566, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to PCF**
end note

"NRF" -> "PCF": 567, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to PCF**
end note

"NRF" -> "PCF": 568, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to PCF**
end note

"NRF" -> "PCF": 569, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to PCF**
end note

"PCF" -> "NRF": 570, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 571, HTTP/2 req.\nPOST  /nnrf-nfm/v1/subscriptions

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 572, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**PCF to NRF**
end note

"PCF" -> "NRF": 573, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**PCF to NRF**
end note

"NRF" -> "PCF": 576, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to PCF**
end note

"NRF" -> "PCF": 577, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to PCF**
end note

"NRF" -> "PCF": 578, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to PCF**
end note

"NRF" -> "PCF": 579, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to PCF**
end note

"NSSF" -> "NRF": 604, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/3c1774e6-f5a8-41ed-ba4e-c32b10ea0d21

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 605, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/3c1774e6-f5a8-41ed-ba4e-c32b10ea0d21

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 612, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NSSF to NRF**
end note

"NSSF" -> "NRF": 613, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NSSF to NRF**
end note

"NRF" -> "NSSF": 618, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to NSSF**
end note

"NRF" -> "NSSF": 619, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to NSSF**
end note

"NRF" -> "NSSF": 620, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to NSSF**
end note

"NRF" -> "NSSF": 621, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to NSSF**
end note

"NRF" -> "NSSF": 622, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to NSSF**
end note

"NRF" -> "NSSF": 623, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to NSSF**
end note

"SMF" -> "UPF": 631, PFCP req.\nPFCP Association Setup Request (5)

note right #03B5AA
**SMF to UPF**
end note

"UPF" -> "SMF": 633, PFCP,ICMP req.\nPFCP Association Setup Request (5)

note right #03B5AA
**UPF to SMF**
end note

"BSF" -> "NRF": 660, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/3c96ae14-f5a8-41ed-8877-3100fc40cf52

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 661, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/3c96ae14-f5a8-41ed-8877-3100fc40cf52

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 668, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**BSF to NRF**
end note

"BSF" -> "NRF": 669, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**BSF to NRF**
end note

"NRF" -> "BSF": 674, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to BSF**
end note

"NRF" -> "BSF": 675, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to BSF**
end note

"NRF" -> "BSF": 676, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to BSF**
end note

"NRF" -> "BSF": 677, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to BSF**
end note

"NRF" -> "BSF": 678, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to BSF**
end note

"NRF" -> "BSF": 679, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to BSF**
end note

"UDR" -> "NRF": 733, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/3ca68154-f5a8-41ed-9303-53ed3db54da8

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 734, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/3ca68154-f5a8-41ed-9303-53ed3db54da8

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 741, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDR to NRF**
end note

"UDR" -> "NRF": 742, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDR to NRF**
end note

"NRF" -> "UDR": 747, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to UDR**
end note

"NRF" -> "UDR": 748, HTTP/2 201 rsp.

note right #D7FEFC
**NRF to UDR**
end note

"NRF" -> "UDR": 749, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to UDR**
end note

"NRF" -> "UDR": 750, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to UDR**
end note

"NRF" -> "UDR": 757, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to UDR**
end note

"NRF" -> "UDR": 758, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to UDR**
end note

"SMF" -> "UPF": 812, PFCP req.\nPFCP Association Setup Request (5)

note right #03B5AA
**SMF to UPF**
end note

"UPF" -> "SMF": 814, PFCP,ICMP req.\nPFCP Association Setup Request (5)

note right #03B5AA
**UPF to SMF**
end note

"AMF" -> "NRF": 970, HTTP/2 req.\nPUT  /nnrf-nfm/v1/nf-instances/3a52609e-f5a8-41ed-956c-a9071229793c

note right #03B5AA
**AMF to NRF**
end note

@enduml
