@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "UE_1"
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "SGWU"
participant "SGWC"
participant "UDM"
participant "UDR"
participant "NRF"
participant "8.8.8.8"
participant "BSF"
participant "NSSF"
participant "AUSF"
participant "PCF"


"AMF" -> "UDM": 1693, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to UDM**
end note

"UDM" -> "UDR": 1705, HTTP/2 req.\nPUT  /nudr-dr/v1/subscription-data/imsi-901700000000004/context-data/amf-3gpp-access\nPUT  /nudr-dr/v1/subscription-data/imsi-901700000000004/context-data/amf-3gpp-access

note right #03B5AA
**UDM to UDR**
end note

"UDM" -> "UDR": 1709, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDM to UDR**
end note

"UDR" -> "UDM": 1713, HTTP/2 204 rsp.

note right #D7FEFC
**UDR to UDM**
end note


"UDM" -> "AMF": 1719, HTTP/2 201 rsp.

note right #D7FEFC
**UDM to AMF**
end note

"UDM" -> "AMF": 1723, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDM to AMF**
end note

"AMF" -> "NRF": 1725, HTTP/2 req.\nGET  /nnrf-disc/v1/nf-instances

note right #03B5AA
**AMF to NRF**
end note

"NRF" -> "AMF": 1727, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to AMF**
end note


"NRF" -> "AMF": 1729, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note

"AMF" -> "UDM": 1733, HTTP/2 req.\nGET  /nudm-sdm/v2/imsi-901700000000004/am-data

note right #03B5AA
**AMF to UDM**
end note

"UDM" -> "UDR": 1735, HTTP/2 req.\nGET  /nudr-dr/v1/subscription-data/imsi-901700000000004/90170/provisioned-data/am-data\nPUT  /nudr-dr/v1/subscription-data/imsi-901700000000004/90170/provisioned-data/am-data

note right #03B5AA
**UDM to UDR**
end note

"UDR" -> "UDM": 1740, HTTP/2 200 rsp.

note right #D7FEFC
**UDR to UDM**
end note

"UDR" -> "UDM": 1742, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDR to UDM**
end note

"UDM" -> "AMF": 1746, HTTP/2 200 rsp.

note right #D7FEFC
**UDM to AMF**
end note

"UDM" -> "AMF": 1748, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDM to AMF**
end note

"AMF" -> "UDM": 1752, HTTP/2 req.\nGET  /nudm-sdm/v2/imsi-901700000000004/smf-select-data

note right #03B5AA
**AMF to UDM**
end note


"UDM" -> "UDR": 1754, HTTP/2 req.\nGET  /nudr-dr/v1/subscription-data/imsi-901700000000004/90170/provisioned-data/smf-selection-subscription-data

note right #03B5AA
**UDM to UDR**
end note


"UDR" -> "UDM": 1758, HTTP/2 200 rsp.

note right #D7FEFC
**UDR to UDM**
end note

"UDR" -> "UDM": 1760, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDR to UDM**
end note

"UDM" -> "AMF": 1764, HTTP/2 200 rsp.

note right #D7FEFC
**UDM to AMF**
end note

"UDM" -> "AMF": 1766, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDM to AMF**
end note


"AMF" -> "UDM": 1770, HTTP/2 req.\nGET  /nudm-sdm/v2/imsi-901700000000004/ue-context-in-smf-data

note right #03B5AA
**AMF to UDM**
end note

"UDM" -> "AMF": 1772, HTTP/2 200 rsp.

note right #D7FEFC
**UDM to AMF**
end note

"UDM" -> "AMF": 1774, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDM to AMF**
end note

"AMF" -> "NRF": 1778, HTTP/2 req.\nGET  /nnrf-disc/v1/nf-instances

note right #03B5AA
**AMF to NRF**
end note

"NRF" -> "AMF": 1780, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1782, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note

"AMF" -> "PCF": 1808, HTTP/2 req.\nPOST  /npcf-am-policy-control/v1/policies

note right #03B5AA
**AMF to PCF**
end note

"AMF" -> "PCF": 1816, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**AMF to PCF**
end note

"PCF" -> "NRF": 1824, HTTP/2 req.\nGET  /nnrf-disc/v1/nf-instances

note right #03B5AA
**PCF to NRF**
end note

"NRF" -> "PCF": 1826, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to PCF**
end note

"NRF" -> "PCF": 1830, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to PCF**
end note

"PCF" -> "UDR": 1856, HTTP/2 req.\nGET  /nudr-dr/v1/policy-data/ues/imsi-901700000000004/am-data

note right #03B5AA
**PCF to UDR**
end note

"UDR" -> "PCF": 1864, HTTP/2 200 rsp.

note right #D7FEFC
**UDR to PCF**
end note

"UDR" -> "PCF": 1866, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**UDR to PCF**
end note

"PCF" -> "AMF": 1874, HTTP/2 201 rsp.

note right #D7FEFC
**PCF to AMF**
end note

"PCF" -> "AMF": 1876, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**PCF to AMF**
end note

"AMF" -> "gNB": 1880, NGAP InitialContextSetup (14),\nNAS Registration accept (0x42)

note right #CDDCF3
**AMF to gNB**
end note

"gNB" -> "AMF": 1882, NGAP InitialContextSetup (14)

note right #CDDCF3
**gNB to AMF**
end note

"gNB" -> "AMF": 1903, NGAP UplinkNASTransport (46),\nNAS Registration complete (0x43),\nNAS UL NAS transport (0x67),\nNAS PDU session establishment request (0xc1)

note right #285AA4
**gNB to AMF**
end note

"AMF" -> "gNB": 1905, NGAP DownlinkNASTransport (4),\nNAS Configuration update command (0x54)

note right #CDDCF3
**AMF to gNB**
end note

"AMF" -> "NRF": 1907, HTTP/2 req.\nGET  /nnrf-disc/v1/nf-instances

note right #03B5AA
**AMF to NRF**
end note

"NRF" -> "AMF": 1909, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to AMF**
end note


"NRF" -> "AMF": 1911, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note


"AMF" -> "NSSF": 1937, HTTP/2 req.\nGET  /nnssf-nsselection/v2/network-slice-information

note right #03B5AA
**AMF to NSSF**
end note


"NSSF" -> "AMF": 1943, HTTP/2 200 rsp.

note right #D7FEFC
**NSSF to AMF**
end note


"NSSF" -> "AMF": 1945, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NSSF to AMF**
end note


"AMF" -> "NRF": 1949, HTTP/2 req.\nGET  /nnrf-disc/v1/nf-instances

note right #03B5AA
**AMF to NRF**
end note


"NRF" -> "AMF": 1951, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1953, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #D7FEFC
**NRF to AMF**
end note


"AMF" -> "gNB": 1957, NGAP DownlinkNASTransport (4),\nNAS DL NAS transport (0x68),\nNAS PDU session establishment request (0xc1)

note right #285AA4
**AMF to gNB**
end note


@enduml
