@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "SGWU"
participant "SGWC"
participant "AUSF"
participant "UDM"
participant "UDR"
participant "NRF"
participant "BSF"
participant "NSSF"
participant "8.8.8.8"
participant "PCF"

"PCF" -> "NRF": 1197, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/3bda8e00-f5a8-41ed-8b25-8778ac8a932f

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 1198, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/3bda8e00-f5a8-41ed-8b25-8778ac8a932f

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 1199, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 1200, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"NRF" -> "PCF": 1203, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to PCF**
end note

"NRF" -> "PCF": 1204, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to PCF**
end note

"NSSF" -> "NRF": 1209, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/3c1774e6-f5a8-41ed-ba4e-c32b10ea0d21

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 1210, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/3c1774e6-f5a8-41ed-ba4e-c32b10ea0d21

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 1211, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 1212, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NRF" -> "NSSF": 1215, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to NSSF**
end note

"NRF" -> "NSSF": 1216, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to NSSF**
end note

"BSF" -> "NRF": 1256, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/3c96ae14-f5a8-41ed-8877-3100fc40cf52

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 1257, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/3c96ae14-f5a8-41ed-8877-3100fc40cf52

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 1258, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 1259, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"NRF" -> "BSF": 1262, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to BSF**
end note

"NRF" -> "BSF": 1263, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to BSF**
end note

"UDR" -> "NRF": 1266, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/3ca68154-f5a8-41ed-9303-53ed3db54da8

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 1267, HTTP/2 req.\nPATCH  /nnrf-nfm/v1/nf-instances/3ca68154-f5a8-41ed-9303-53ed3db54da8

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 1268, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 1269, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"NRF" -> "UDR": 1272, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to UDR**
end note

"NRF" -> "UDR": 1273, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to UDR**
end note

"gNB" -> "AMF": 1284, NGAP NGSetup (21)

note right #CDDCF3
**gNB to AMF**
end note

"AMF" -> "gNB": 1288, NGAP NGSetup (21)

note right #CDDCF3
**AMF to gNB**
end note

"gNB" -> "AMF": 1450, NGAP InitialUEMessage (15),\nNAS Registration request (0x41)

note right #285AA4
**gNB to AMF**
end note

"AMF" -> "NRF": 1452, HTTP/2 req.\nGET  /nnrf-disc/v1/nf-instances

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 1453, HTTP/2 req.\nGET  /nnrf-disc/v1/nf-instances

note right #03B5AA
**AMF to NRF**
end note

"NRF" -> "AMF": 1454, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1455, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1456, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"NRF" -> "AMF": 1457, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"AMF" -> "AUSF": 1478, HTTP/2 req.\nPOST  /nausf-auth/v1/ue-authentications

note right #03B5AA
**AMF to AUSF**
end note

"AMF" -> "AUSF": 1479, HTTP/2 req.\nPOST  /nausf-auth/v1/ue-authentications

note right #03B5AA
**AMF to AUSF**
end note

"AMF" -> "AUSF": 1482, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to AUSF**
end note

"AMF" -> "AUSF": 1483, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to AUSF**
end note

"AUSF" -> "NRF": 1490, HTTP/2 req.\nGET  /nnrf-disc/v1/nf-instances

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 1491, HTTP/2 req.\nGET  /nnrf-disc/v1/nf-instances

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "AUSF": 1492, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to AUSF**
end note

"NRF" -> "AUSF": 1493, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to AUSF**
end note

"NRF" -> "AUSF": 1496, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"NRF" -> "AUSF": 1497, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"AUSF" -> "UDM": 1524, HTTP/2 req.\nPOST  /nudm-ueau/v1/suci-0-901-70-0000-0-0-0000000004/security-information/generate-auth-data

note right #03B5AA
**AUSF to UDM**
end note

"AUSF" -> "UDM": 1525, HTTP/2 req.\nPOST  /nudm-ueau/v1/suci-0-901-70-0000-0-0-0000000004/security-information/generate-auth-data

note right #03B5AA
**AUSF to UDM**
end note

"AUSF" -> "UDM": 1532, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to UDM**
end note

"AUSF" -> "UDM": 1533, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to UDM**
end note

"UDM" -> "NRF": 1536, HTTP/2 req.\nGET  /nnrf-disc/v1/nf-instances\nPATCH  /nnrf-disc/v1/nf-instances

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 1537, HTTP/2 req.\nGET  /nnrf-disc/v1/nf-instances\nPATCH  /nnrf-disc/v1/nf-instances

note right #03B5AA
**UDM to NRF**
end note

"NRF" -> "UDM": 1538, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to UDM**
end note

"NRF" -> "UDM": 1539, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to UDM**
end note

"NRF" -> "UDM": 1542, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDM**
end note

"NRF" -> "UDM": 1543, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDM**
end note

"UDM" -> "UDR": 1570, HTTP/2 req.\nGET  /nudr-dr/v1/subscription-data/imsi-901700000000004/authentication-data/authentication-subscription

note right #03B5AA
**UDM to UDR**
end note

"UDM" -> "UDR": 1571, HTTP/2 req.\nGET  /nudr-dr/v1/subscription-data/imsi-901700000000004/authentication-data/authentication-subscription

note right #03B5AA
**UDM to UDR**
end note

"UDR" -> "UDM": 1585, HTTP/2 200 rsp.

note right #D7FEFC
**UDR to UDM**
end note

"UDR" -> "UDM": 1586, HTTP/2 200 rsp.

note right #D7FEFC
**UDR to UDM**
end note

"UDR" -> "UDM": 1587, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to UDM**
end note

"UDR" -> "UDM": 1588, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to UDM**
end note

"UDM" -> "AUSF": 1593, HTTP/2 200 rsp.

note right #D7FEFC
**UDM to AUSF**
end note

"UDM" -> "AUSF": 1594, HTTP/2 200 rsp.

note right #D7FEFC
**UDM to AUSF**
end note

"UDM" -> "AUSF": 1595, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to AUSF**
end note

"UDM" -> "AUSF": 1596, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to AUSF**
end note

"AUSF" -> "AMF": 1601, HTTP/2 201 rsp.

note right #D7FEFC
**AUSF to AMF**
end note

"AUSF" -> "AMF": 1602, HTTP/2 201 rsp.

note right #D7FEFC
**AUSF to AMF**
end note

"AUSF" -> "AMF": 1603, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to AMF**
end note

"AUSF" -> "AMF": 1604, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to AMF**
end note

"AMF" -> "gNB": 1607, NGAP DownlinkNASTransport (4),\nNAS Authentication request (0x56)

note right #285AA4
**AMF to gNB**
end note

"gNB" -> "AMF": 1609, NGAP UplinkNASTransport (46),\nNAS Authentication response (0x57)

note right #CDDCF3
**gNB to AMF**
end note

"AMF" -> "AUSF": 1611, HTTP/2 req.\nPUT  /nausf-auth/v1/ue-authentications/1/5g-aka-confirmation

note right #03B5AA
**AMF to AUSF**
end note

"AMF" -> "AUSF": 1612, HTTP/2 req.\nPUT  /nausf-auth/v1/ue-authentications/1/5g-aka-confirmation

note right #03B5AA
**AMF to AUSF**
end note

"AMF" -> "AUSF": 1615, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to AUSF**
end note

"AMF" -> "AUSF": 1616, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to AUSF**
end note

"AUSF" -> "UDM": 1619, HTTP/2 req.\nPOST  /nudm-ueau/v1/imsi-901700000000004/auth-events

note right #03B5AA
**AUSF to UDM**
end note

"AUSF" -> "UDM": 1620, HTTP/2 req.\nPOST  /nudm-ueau/v1/imsi-901700000000004/auth-events

note right #03B5AA
**AUSF to UDM**
end note

"AUSF" -> "UDM": 1623, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to UDM**
end note

"AUSF" -> "UDM": 1624, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to UDM**
end note

"UDM" -> "UDR": 1627, HTTP/2 req.\nPUT  /nudr-dr/v1/subscription-data/imsi-901700000000004/authentication-data/authentication-status

note right #03B5AA
**UDM to UDR**
end note

"UDM" -> "UDR": 1628, HTTP/2 req.\nPUT  /nudr-dr/v1/subscription-data/imsi-901700000000004/authentication-data/authentication-status\nPUT  /nudr-dr/v1/subscription-data/imsi-901700000000004/authentication-data/authentication-status

note right #03B5AA
**UDM to UDR**
end note

"UDM" -> "UDR": 1631, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to UDR**
end note

"UDM" -> "UDR": 1632, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to UDR**
end note

"UDR" -> "UDM": 1642, HTTP/2 204 rsp.

note right #D7FEFC
**UDR to UDM**
end note

"UDR" -> "UDM": 1643, HTTP/2 204 rsp.

note right #D7FEFC
**UDR to UDM**
end note

"UDM" -> "AUSF": 1644, HTTP/2 201 rsp.

note right #D7FEFC
**UDM to AUSF**
end note

"UDM" -> "AUSF": 1645, HTTP/2 201 rsp.

note right #D7FEFC
**UDM to AUSF**
end note

"UDM" -> "AUSF": 1646, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to AUSF**
end note

"UDM" -> "AUSF": 1647, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to AUSF**
end note

"AUSF" -> "AMF": 1650, HTTP/2 200 rsp.

note right #D7FEFC
**AUSF to AMF**
end note

"AUSF" -> "AMF": 1651, HTTP/2 200 rsp.

note right #D7FEFC
**AUSF to AMF**
end note

"AUSF" -> "AMF": 1652, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to AMF**
end note

"AUSF" -> "AMF": 1653, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to AMF**
end note

"AMF" -> "gNB": 1656, NGAP DownlinkNASTransport (4),\nNAS Security mode command (0x5d)

note right #CDDCF3
**AMF to gNB**
end note

"gNB" -> "AMF": 1658, NGAP UplinkNASTransport (46),\nNAS Security mode complete (0x5e),\nNAS Registration request (0x41)

note right #285AA4
**gNB to AMF**
end note

"AMF" -> "NRF": 1662, HTTP/2 req.\nGET  /nnrf-disc/v1/nf-instances

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 1663, HTTP/2 req.\nGET  /nnrf-disc/v1/nf-instances

note right #03B5AA
**AMF to NRF**
end note

"NRF" -> "AMF": 1664, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1665, HTTP/2 200 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 1666, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"NRF" -> "AMF": 1667, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"AMF" -> "UDM": 1688, HTTP/2 req.\nPUT  /nudm-uecm/v1/imsi-901700000000004/registrations/amf-3gpp-access

note right #03B5AA
**AMF to UDM**
end note

@enduml
