@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "UE_2"
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "UDM"
participant "NSSF"
participant "NRF"
participant "AUSF"
participant "BSF"
participant "UDR"
participant "PCF"

"BSF" -> "NRF": 49, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 50, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 51, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 52, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"NRF" -> "BSF": 55, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to BSF**
end note

"NRF" -> "BSF": 56, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to BSF**
end note

"NSSF" -> "NRF": 59, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 60, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 61, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 62, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NRF" -> "NSSF": 65, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to NSSF**
end note

"NRF" -> "NSSF": 66, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NSSF**
end note

"UDR" -> "NRF": 69, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 70, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 71, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 72, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"PCF" -> "NRF": 73, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 74, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 75, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 76, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"NRF" -> "UDR": 81, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to UDR**
end note

"NRF" -> "UDR": 82, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDR**
end note

"NRF" -> "PCF": 85, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to PCF**
end note

"NRF" -> "PCF": 86, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"gNB" -> "AMF": 172, NGAP UplinkNASTransport (46),\nNAS UL NAS transport (0x67),\nNAS PDU session establishment request (0xc1)

note right #285AA4
**gNB to AMF**
end note

"AMF" -> "gNB": 174, NGAP DownlinkNASTransport (4),\nNAS 5GMM status (0x64)

note right #CDDCF3
**AMF to gNB**
end note

"SMF" -> "NRF": 178, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 179, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 180, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 181, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"NRF" -> "SMF": 184, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to SMF**
end note

"NRF" -> "SMF": 185, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to SMF**
end note

"AMF" -> "NRF": 196, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 197, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 198, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 199, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"NRF" -> "AMF": 202, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to AMF**
end note

"NRF" -> "AMF": 203, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"UDM" -> "NRF": 218, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 219, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 220, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 221, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"AUSF" -> "NRF": 222, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 223, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 224, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 225, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "UDM": 230, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to UDM**
end note

"NRF" -> "UDM": 231, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDM**
end note

"NRF" -> "AUSF": 234, HTTP/2 204 rsp.

note right #D7FEFC
**NRF to AUSF**
end note

"NRF" -> "AUSF": 235, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"BSF" -> "NRF": 401, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 402, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 403, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 404, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"NRF" -> "BSF": 407, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to BSF**
end note

"NRF" -> "BSF": 408, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to BSF**
end note

"NSSF" -> "NRF": 411, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 412, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 413, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 414, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NRF" -> "NSSF": 417, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NSSF**
end note

"NRF" -> "NSSF": 418, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NSSF**
end note

"PCF" -> "NRF": 421, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 422, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 423, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 424, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"UDR" -> "NRF": 425, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 426, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 427, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 428, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"NRF" -> "PCF": 433, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "PCF": 434, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "UDR": 437, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDR**
end note

"NRF" -> "UDR": 438, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDR**
end note

"SMF" -> "NRF": 538, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 539, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 540, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 541, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"NRF" -> "SMF": 544, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to SMF**
end note

"NRF" -> "SMF": 545, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to SMF**
end note

"AMF" -> "NRF": 553, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 554, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 555, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 556, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"NRF" -> "AMF": 559, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"NRF" -> "AMF": 560, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"UDM" -> "NRF": 563, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 564, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 565, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 566, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"AUSF" -> "NRF": 567, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 568, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 569, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 570, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "UDM": 575, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDM**
end note

"NRF" -> "UDM": 576, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDM**
end note

"NRF" -> "AUSF": 579, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"NRF" -> "AUSF": 580, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"gNB" -> "AMF": 750, NGAP UplinkNASTransport (46),\nNAS UL NAS transport (0x67),\nNAS PDU session establishment request (0xc1)

note right #285AA4
**gNB to AMF**
end note

"AMF" -> "gNB": 752, NGAP DownlinkNASTransport (4),\nNAS 5GMM status (0x64)

note right #CDDCF3
**AMF to gNB**
end note

@enduml
