@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "UE_2"
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "BSF"
participant "UDM"
participant "NRF"
participant "AUSF"
participant "UDR"
participant "PCF"
participant "NSSF"

"BSF" -> "NRF": 2782, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 2783, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 2784, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 2785, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"NRF" -> "BSF": 2788, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to BSF**
end note

"NRF" -> "BSF": 2789, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to BSF**
end note

"NSSF" -> "NRF": 2792, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 2793, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 2794, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 2795, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NRF" -> "NSSF": 2798, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NSSF**
end note

"NRF" -> "NSSF": 2799, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NSSF**
end note

"UDR" -> "NRF": 2802, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 2803, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 2804, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 2805, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"PCF" -> "NRF": 2806, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 2807, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 2808, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 2809, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"NRF" -> "UDR": 2814, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDR**
end note

"NRF" -> "UDR": 2815, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDR**
end note

"NRF" -> "PCF": 2818, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "PCF": 2819, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"SMF" -> "NRF": 2883, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 2884, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 2885, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 2886, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"NRF" -> "SMF": 2889, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to SMF**
end note

"NRF" -> "SMF": 2890, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to SMF**
end note

"AMF" -> "NRF": 2897, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 2898, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 2899, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 2900, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"NRF" -> "AMF": 2903, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"NRF" -> "AMF": 2904, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"UDM" -> "NRF": 2910, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 2911, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 2912, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 2913, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"AUSF" -> "NRF": 2914, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 2915, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 2916, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 2917, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "UDM": 2922, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDM**
end note

"NRF" -> "UDM": 2923, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDM**
end note

"NRF" -> "AUSF": 2926, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"NRF" -> "AUSF": 2927, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"BSF" -> "NRF": 3126, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 3127, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 3128, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 3129, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"NRF" -> "BSF": 3132, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to BSF**
end note

"NRF" -> "BSF": 3133, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to BSF**
end note

"NSSF" -> "NRF": 3136, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 3137, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 3138, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 3139, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NRF" -> "NSSF": 3142, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NSSF**
end note

"NRF" -> "NSSF": 3143, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NSSF**
end note

"PCF" -> "NRF": 3146, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 3147, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 3148, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 3149, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"UDR" -> "NRF": 3150, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 3151, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 3152, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 3153, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"NRF" -> "PCF": 3158, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "PCF": 3159, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "UDR": 3162, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDR**
end note

"NRF" -> "UDR": 3163, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDR**
end note

"SMF" -> "NRF": 3244, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 3245, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 3246, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 3247, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"NRF" -> "SMF": 3250, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to SMF**
end note

"NRF" -> "SMF": 3251, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to SMF**
end note

"AMF" -> "NRF": 3254, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 3255, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 3256, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 3257, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"NRF" -> "AMF": 3260, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"NRF" -> "AMF": 3261, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"AUSF" -> "NRF": 3264, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 3265, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 3266, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 3267, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"UDM" -> "NRF": 3268, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 3269, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 3270, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 3271, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"NRF" -> "AUSF": 3276, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"NRF" -> "AUSF": 3277, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"NRF" -> "UDM": 3280, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDM**
end note

"NRF" -> "UDM": 3281, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDM**
end note

"gNB" -> "AMF": 3331, NGAP UplinkNASTransport (46),\nNAS UL NAS transport (0x67),\nNAS PDU session establishment request (0xc1)

note right #285AA4
**gNB to AMF**
end note

"AMF" -> "gNB": 3333, NGAP DownlinkNASTransport (4),\nNAS 5GMM status (0x64)

note right #CDDCF3
**AMF to gNB**
end note

"BSF" -> "NRF": 3465, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 3466, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

@enduml
