@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "UE_2"
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "UDM"
participant "NSSF"
participant "NRF"
participant "AUSF"
participant "BSF"
participant "UDR"
participant "PCF"

"BSF" -> "NRF": 3467, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 3468, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"NRF" -> "BSF": 3471, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to BSF**
end note

"NRF" -> "BSF": 3472, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to BSF**
end note

"NSSF" -> "NRF": 3489, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 3490, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 3491, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 3492, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NRF" -> "NSSF": 3496, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NSSF**
end note

"NRF" -> "NSSF": 3497, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NSSF**
end note

"PCF" -> "NRF": 3500, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 3501, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 3502, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 3503, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"UDR" -> "NRF": 3504, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 3505, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 3506, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 3507, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"NRF" -> "PCF": 3512, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "PCF": 3513, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "UDR": 3516, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDR**
end note

"NRF" -> "UDR": 3517, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDR**
end note

"SMF" -> "NRF": 3596, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 3597, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 3598, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 3599, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"NRF" -> "SMF": 3602, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to SMF**
end note

"NRF" -> "SMF": 3603, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to SMF**
end note

"AMF" -> "NRF": 3606, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 3607, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 3608, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 3609, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"NRF" -> "AMF": 3612, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"NRF" -> "AMF": 3613, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"AUSF" -> "NRF": 3616, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 3617, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 3618, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 3619, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"UDM" -> "NRF": 3620, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 3621, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 3622, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 3623, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"NRF" -> "AUSF": 3628, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"NRF" -> "AUSF": 3629, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"NRF" -> "UDM": 3632, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDM**
end note

"NRF" -> "UDM": 3633, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDM**
end note

"BSF" -> "NRF": 3822, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 3823, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 3824, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 3825, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"NRF" -> "BSF": 3828, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to BSF**
end note

"NRF" -> "BSF": 3829, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to BSF**
end note

"NSSF" -> "NRF": 3832, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 3833, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 3834, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 3835, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NRF" -> "NSSF": 3838, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NSSF**
end note

"NRF" -> "NSSF": 3839, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NSSF**
end note

"UDR" -> "NRF": 3842, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 3843, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 3844, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 3845, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"PCF" -> "NRF": 3846, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 3847, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 3848, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 3849, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"NRF" -> "UDR": 3854, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDR**
end note

"NRF" -> "UDR": 3855, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDR**
end note

"NRF" -> "PCF": 3858, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "PCF": 3859, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"gNB" -> "AMF": 3908, NGAP UplinkNASTransport (46),\nNAS UL NAS transport (0x67),\nNAS PDU session establishment request (0xc1)

note right #285AA4
**gNB to AMF**
end note

"AMF" -> "gNB": 3910, NGAP DownlinkNASTransport (4),\nNAS 5GMM status (0x64)

note right #CDDCF3
**AMF to gNB**
end note

"SMF" -> "NRF": 3962, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 3963, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 3964, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 3965, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"NRF" -> "SMF": 3968, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to SMF**
end note

"NRF" -> "SMF": 3969, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to SMF**
end note

"AMF" -> "NRF": 3975, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 3976, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 3977, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 3978, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"NRF" -> "AMF": 3981, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"NRF" -> "AMF": 3982, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"AUSF" -> "NRF": 3985, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 3986, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 3987, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 3988, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"UDM" -> "NRF": 3989, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 3990, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 3991, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 3992, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"NRF" -> "AUSF": 3997, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"NRF" -> "AUSF": 3998, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"NRF" -> "UDM": 4001, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDM**
end note

"NRF" -> "UDM": 4002, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDM**
end note

"gNB" -> "UPF": 4089, HTTP/2 req.\nPOST  /nsmf-pdusession/v1/sm-contexts/4/release

note right #03B5AA
**gNB to UPF**
end note

"UE_2" -> "SMF": 4090, HTTP/2 req.\nPOST  /nsmf-pdusession/v1/sm-contexts/4/release

note right #03B5AA
**UE_2 to SMF**
end note

"UPF" -> "SMF": 4091, HTTP/2 req.\nPOST  /nsmf-pdusession/v1/sm-contexts/4/release

note right #03B5AA
**UPF to SMF**
end note

"UPF" -> "SMF": 4092, HTTP/2 req.\nPOST  /nsmf-pdusession/v1/sm-contexts/4/release

note right #03B5AA
**UPF to SMF**
end note

@enduml
