@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "UE_2"
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "UDM"
participant "NSSF"
participant "NRF"
participant "AUSF"
participant "BSF"
participant "UDR"
participant "PCF"

"SMF" -> "PCF": 4125, HTTP/2 req.\nPOST  /npcf-smpolicycontrol/v1/sm-policies/4/delete

note right #03B5AA
**SMF to PCF**
end note

"SMF" -> "PCF": 4126, HTTP/2 req.\nPOST  /npcf-smpolicycontrol/v1/sm-policies/4/delete

note right #03B5AA
**SMF to PCF**
end note

"SMF" -> "PCF": 4129, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to PCF**
10.0.14.1 to 10.0.10.1 (IPs)
HTTP/2 stream 1 payload
{
  "servingNetwork": {
    "mcc": "901",
    "mnc": "70"
  }
}

end note

"SMF" -> "PCF": 4130, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to PCF**
end note

"PCF" -> "BSF": 4157, HTTP/2 req.\nDELETE  /nbsf-management/v1/pcfBindings/4

note right #03B5AA
**PCF to BSF**
end note

"PCF" -> "BSF": 4158, HTTP/2 req.\nDELETE  /nbsf-management/v1/pcfBindings/4

note right #03B5AA
**PCF to BSF**
end note

"BSF" -> "PCF": 4173, HTTP/2 204 rsp.

note right #D7FEFC
**BSF to PCF**
end note

"BSF" -> "PCF": 4174, HTTP/2 204 rsp.

note right #D7FEFC
**BSF to PCF**
end note

"PCF" -> "SMF": 4181, HTTP/2 204 rsp.

note right #D7FEFC
**PCF to SMF**
end note

"PCF" -> "SMF": 4182, HTTP/2 204 rsp.

note right #D7FEFC
**PCF to SMF**
end note

"SMF" -> "UPF": 4185, PFCP req.\nPFCP Session Deletion Request (54)

note right #03B5AA
**SMF to UPF**
end note

"UPF" -> "SMF": 4187, PFCP rsp.\nPFCP Session Deletion Response (55)

note right #D7FEFC
**UPF to SMF**
end note

"UPF" -> "SMF": 4188, PFCP rsp.\nPFCP Session Deletion Response (55)

note right #D7FEFC
**UPF to SMF**
end note

"SMF" -> "UPF": 4193, HTTP/2 204 rsp.

note right #D7FEFC
**SMF to UPF**
end note

"SMF" -> "UPF": 4194, HTTP/2 204 rsp.

note right #D7FEFC
**SMF to UPF**
end note

"UPF" -> "gNB": 4195, HTTP/2 204 rsp.

note right #D7FEFC
**UPF to gNB**
end note

"SMF" -> "UE_2": 4196, HTTP/2 204 rsp.

note right #D7FEFC
**SMF to UE_2**
end note

"SMF" -> "UPF": 4199, HTTP/2 204 rsp.

note right #D7FEFC
**SMF to UPF**
end note

"SMF" -> "UPF": 4200, HTTP/2 204 rsp.

note right #D7FEFC
**SMF to UPF**
end note

"UPF" -> "gNB": 4209, HTTP/2 204 rsp.

note right #D7FEFC
**UPF to gNB**
end note

"SMF" -> "UE_2": 4210, HTTP/2 204 rsp.

note right #D7FEFC
**SMF to UE_2**
end note

"BSF" -> "NRF": 4336, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 4337, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 4338, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 4339, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"NRF" -> "BSF": 4342, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to BSF**
end note

"NRF" -> "BSF": 4343, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to BSF**
end note

"NSSF" -> "NRF": 4346, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 4347, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 4348, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 4349, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NRF" -> "NSSF": 4352, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NSSF**
end note

"NRF" -> "NSSF": 4353, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NSSF**
end note

"PCF" -> "NRF": 4356, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 4357, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 4358, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 4359, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"NRF" -> "PCF": 4362, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "PCF": 4363, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"UDR" -> "NRF": 4366, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 4367, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 4368, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 4369, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"NRF" -> "UDR": 4372, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDR**
end note

"NRF" -> "UDR": 4373, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDR**
end note

"SMF" -> "NRF": 4485, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 4486, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 4487, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 4488, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"NRF" -> "SMF": 4491, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to SMF**
end note

"NRF" -> "SMF": 4492, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to SMF**
end note

"AMF" -> "NRF": 4495, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 4496, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 4497, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 4498, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"NRF" -> "AMF": 4501, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"NRF" -> "AMF": 4502, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"AUSF" -> "NRF": 4505, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 4506, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 4507, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 4508, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"UDM" -> "NRF": 4509, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 4510, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 4511, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 4512, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"NRF" -> "AUSF": 4517, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"NRF" -> "AUSF": 4518, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"NRF" -> "UDM": 4521, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDM**
end note

"NRF" -> "UDM": 4522, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDM**
end note

"gNB" -> "AMF": 4602, NGAP UplinkNASTransport (46),\nNAS UL NAS transport (0x67),\nNAS PDU session establishment request (0xc1)

note right #285AA4
**gNB to AMF**
end note

"AMF" -> "gNB": 4604, NGAP DownlinkNASTransport (4),\nNAS 5GMM status (0x64)

note right #CDDCF3
**AMF to gNB**
end note

@enduml
