@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "UE_2"
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "BSF"
participant "UDM"
participant "NRF"
participant "AUSF"
participant "UDR"
participant "PCF"
participant "NSSF"

"BSF" -> "NRF": 2096, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 2097, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 2098, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 2099, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"NRF" -> "BSF": 2102, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to BSF**
end note

"NRF" -> "BSF": 2103, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to BSF**
end note

"NSSF" -> "NRF": 2106, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 2107, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 2108, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 2109, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NRF" -> "NSSF": 2112, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NSSF**
end note

"NRF" -> "NSSF": 2113, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NSSF**
end note

"UDR" -> "NRF": 2116, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 2117, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 2118, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 2119, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"PCF" -> "NRF": 2120, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 2121, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 2122, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 2123, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"NRF" -> "UDR": 2128, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDR**
end note

"NRF" -> "UDR": 2129, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDR**
end note

"NRF" -> "PCF": 2132, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "PCF": 2133, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"gNB" -> "AMF": 2188, NGAP UplinkNASTransport (46),\nNAS UL NAS transport (0x67),\nNAS PDU session establishment request (0xc1)

note right #285AA4
**gNB to AMF**
end note

"AMF" -> "gNB": 2190, NGAP DownlinkNASTransport (4),\nNAS 5GMM status (0x64)

note right #CDDCF3
**AMF to gNB**
end note

"SMF" -> "NRF": 2201, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 2202, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 2205, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 2206, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"NRF" -> "SMF": 2209, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to SMF**
end note

"NRF" -> "SMF": 2210, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to SMF**
end note

"AMF" -> "NRF": 2213, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 2214, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 2215, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 2216, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"NRF" -> "AMF": 2219, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"NRF" -> "AMF": 2220, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"UDM" -> "NRF": 2223, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 2224, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 2225, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 2226, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"AUSF" -> "NRF": 2227, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 2228, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 2229, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 2230, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"NRF" -> "UDM": 2235, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDM**
end note

"NRF" -> "UDM": 2236, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDM**
end note

"NRF" -> "AUSF": 2239, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"NRF" -> "AUSF": 2240, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"BSF" -> "NRF": 2445, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 2446, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 2447, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"BSF" -> "NRF": 2448, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**BSF to NRF**
end note

"NRF" -> "BSF": 2451, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to BSF**
end note

"NRF" -> "BSF": 2452, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to BSF**
end note

"NSSF" -> "NRF": 2455, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 2456, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 2457, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NSSF" -> "NRF": 2458, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NSSF to NRF**
end note

"NRF" -> "NSSF": 2461, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NSSF**
end note

"NRF" -> "NSSF": 2462, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NSSF**
end note

"PCF" -> "NRF": 2465, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 2466, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 2467, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"PCF" -> "NRF": 2468, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**PCF to NRF**
end note

"UDR" -> "NRF": 2469, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 2470, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 2471, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"UDR" -> "NRF": 2472, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDR to NRF**
end note

"NRF" -> "PCF": 2477, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "PCF": 2478, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to PCF**
end note

"NRF" -> "UDR": 2481, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDR**
end note

"NRF" -> "UDR": 2482, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDR**
end note

"SMF" -> "NRF": 2546, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 2547, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 2548, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"SMF" -> "NRF": 2549, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to NRF**
end note

"AMF" -> "NRF": 2550, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 2551, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 2552, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"AMF" -> "NRF": 2553, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AMF to NRF**
end note

"NRF" -> "SMF": 2558, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to SMF**
end note

"NRF" -> "SMF": 2559, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to SMF**
end note

"NRF" -> "AMF": 2562, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"NRF" -> "AMF": 2563, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AMF**
end note

"AUSF" -> "NRF": 2570, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 2571, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 2572, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"AUSF" -> "NRF": 2573, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**AUSF to NRF**
end note

"UDM" -> "NRF": 2574, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 2575, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 2576, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"UDM" -> "NRF": 2577, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**UDM to NRF**
end note

"NRF" -> "AUSF": 2582, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"NRF" -> "AUSF": 2583, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to AUSF**
end note

"NRF" -> "UDM": 2586, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDM**
end note

"NRF" -> "UDM": 2587, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to UDM**
end note

"gNB" -> "AMF": 2725, NGAP UplinkNASTransport (46),\nNAS UL NAS transport (0x67),\nNAS PDU session establishment request (0xc1)

note right #285AA4
**gNB to AMF**
end note

"AMF" -> "gNB": 2727, NGAP DownlinkNASTransport (4),\nNAS 5GMM status (0x64)

note right #CDDCF3
**AMF to gNB**
end note

@enduml
