@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "Malicious_UE"
participant "gNB"
participant "UPF"


"gNB" -> "UPF": 4, GTP<PFCP req.>\nPFCP Association Setup Request (5)

note right #03B5AA
**gNB to UPF**
end note


"Malicious_UE" -> "UPF": 5, PFCP req.\nPFCP Association Setup Request (5)

note right #FFC2D9
**gNB to UPF**
end note

"UPF" -> "Malicious_UE": 6, PFCP rsp.\nPFCP Association Setup Response (6)

note right #FFEAC2
**UPF to Malicious_UE**
end note

"UPF" -> "gNB": 7, PFCP,GTP<ICMP> rsp.\nPFCP Association Setup Response (6)

note right #D7FEFC
**UPF to gNB**
end note

"gNB" -> "UPF": 8, GTP<PFCP req.>\nPFCP Association Setup Request (5)

note right #03B5AA
**gNB to UPF**
end note

"Malicious_UE" -> "UPF": 9, PFCP req.\nPFCP Session Establishment Request (50)

note right #FFC2D9
**Malicious_UE to UPF**
end note

"UPF" -> "Malicious_UE": 10, PFCP rsp.\nPFCP Session Establishment Response (51)

note right #FFEAC2
**UPF to Malicious_UE**
Accept
end note

"UPF" -> "gNB": 11, GTP<PFCP rsp.>\nPFCP Session Establishment Response (51)

note right #D7FEFC
**UPF to gNB**
end note
@enduml
