@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "UE_1"
participant "UE_2"
participant "UE_3"
participant "gNB"
participant "SMF"
participant "UPF"
participant "NRF"
participant "BSF"
participant "10.45.0.5"
participant "PCF"
participant "8.8.8.8"

"8.8.8.8" -> "UE_2": 3645, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UE_2**
end note

"UPF" -> "gNB": 3646, GTPv2,GTP<ICMP> ping rsp.

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 3661, HTTP/2,GTPv2 req., rsp. or notification

note right #EDFEC2
**gNB to UPF**
end note

"UE_1" -> "SMF": 3663, HTTP/2 req.\nPOST  /nsmf-pdusession/v1/sm-contexts/1/modify

note right #03B5AA
**UE_1 to SMF**
end note

"SMF" -> "UE_1": 3666, HTTP/2 400 rsp.

note right #D7FEFC
**SMF to UE_1**
end note

"SMF" -> "UE_1": 3667, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to UE_1**
end note

"UPF" -> "gNB": 3671, HTTP/2,GTPv2 req., rsp. or notification

note right #EDFEC2
**UPF to gNB**
end note

"UPF" -> "gNB": 3672, HTTP/2,GTPv2 req., rsp. or notification

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 3705, HTTP/2,GTPv2 req., rsp. or notification

note right #EDFEC2
**gNB to UPF**
end note

"UE_1" -> "SMF": 3706, HTTP/2 req.\nPOST  /nsmf-pdusession/v1/sm-contexts/2/modify

note right #03B5AA
**UE_1 to SMF**
end note

"SMF" -> "UE_1": 3709, HTTP/2 400 rsp.

note right #D7FEFC
**SMF to UE_1**
end note

"SMF" -> "UE_1": 3710, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to UE_1**
end note

"UPF" -> "gNB": 3714, HTTP/2,GTPv2 req., rsp. or notification

note right #EDFEC2
**UPF to gNB**
end note

"UPF" -> "gNB": 3715, HTTP/2,GTPv2 req., rsp. or notification

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 3753, HTTP/2,GTPv2 req., rsp. or notification

note right #EDFEC2
**gNB to UPF**
end note

"UE_1" -> "SMF": 3754, HTTP/2 req.\nPOST  /nsmf-pdusession/v1/sm-contexts/3/modify

note right #03B5AA
**UE_1 to SMF**
end note

"SMF" -> "UE_1": 3757, HTTP/2 400 rsp.

note right #D7FEFC
**SMF to UE_1**
end note

"SMF" -> "UE_1": 3758, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to UE_1**
end note

"UPF" -> "gNB": 3761, HTTP/2,GTPv2 req., rsp. or notification

note right #EDFEC2
**UPF to gNB**
end note

"UPF" -> "gNB": 3762, HTTP/2,GTPv2 req., rsp. or notification

note right #EDFEC2
**UPF to gNB**
end note

"SMF" -> "UE_1": 3763, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to UE_1**
end note

"UPF" -> "gNB": 3764, HTTP/2,GTPv2 req., rsp. or notification

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 3799, GTPv2,GTP<ICMP> ping req.

note right #5C8001
**gNB to UPF**
end note

"UE_2" -> "8.8.8.8": 3800, ICMP ping req.

note right #5C8001
**UE_2 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 3801, ICMP ping req.

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 3804, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_2": 3805, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UE_2**
end note

"UPF" -> "gNB": 3807, GTPv2,GTP<ICMP> ping rsp.

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 3809, GTPv2,GTP<ICMP> ping req.

note right #5C8001
**gNB to UPF**
end note

"UE_3" -> "8.8.8.8": 3810, ICMP ping req.

note right #5C8001
**UE_3 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 3811, ICMP ping req.

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 3817, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_3": 3818, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UE_3**
end note

"UPF" -> "gNB": 3819, GTPv2,GTP<ICMP> ping rsp.

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 3822, HTTP/2,GTPv2 req., rsp. or notification

note right #EDFEC2
**gNB to UPF**
end note

"UE_1" -> "SMF": 3824, HTTP/2 req.\nPOST  /nsmf-pdusession/v1/sm-contexts/4/modify

note right #03B5AA
**UE_1 to SMF**
end note

"SMF" -> "UE_1": 3829, HTTP/2 400 rsp.

note right #D7FEFC
**SMF to UE_1**
end note

"SMF" -> "UE_1": 3830, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to UE_1**
end note

"UPF" -> "gNB": 3836, HTTP/2,GTPv2 req., rsp. or notification

note right #EDFEC2
**UPF to gNB**
end note

"UPF" -> "gNB": 3838, HTTP/2,GTPv2 req., rsp. or notification

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 3859, HTTP/2,GTPv2 req., rsp. or notification

note right #EDFEC2
**gNB to UPF**
end note

"UE_1" -> "SMF": 3860, HTTP/2 req.\nPOST  /nsmf-pdusession/v1/sm-contexts/5/modify

note right #03B5AA
**UE_1 to SMF**
end note

"SMF" -> "UE_1": 3870, HTTP/2 404 rsp.

note right #D7FEFC
**SMF to UE_1**
end note

"SMF" -> "UE_1": 3871, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to UE_1**
end note

"SMF" -> "UE_1": 3873, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**SMF to UE_1**
end note

"UPF" -> "gNB": 3874, HTTP/2,GTPv2 req., rsp. or notification

note right #EDFEC2
**UPF to gNB**
end note

"UPF" -> "gNB": 3875, HTTP/2,GTPv2 req., rsp. or notification

note right #EDFEC2
**UPF to gNB**
end note

"UPF" -> "gNB": 3876, HTTP/2,GTPv2 req., rsp. or notification

note right #EDFEC2
**UPF to gNB**
end note

"SMF" -> "UE_1": 3877, HTTP/2 404 rsp.

note right #D7FEFC
**SMF to UE_1**
end note

"gNB" -> "UPF": 3883, GTPv2,GTP<ICMP> ping req.

note right #5C8001
**gNB to UPF**
end note

"UPF" -> "gNB": 3884, HTTP/2,GTPv2 req., rsp. or notification

note right #EDFEC2
**UPF to gNB**
end note

"UE_3" -> "8.8.8.8": 3895, ICMP ping req.

note right #5C8001
**UE_3 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 3896, ICMP ping req.

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 3898, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_3": 3899, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UE_3**
end note

"UPF" -> "gNB": 3907, GTPv2,GTP<ICMP> ping rsp.

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 3945, GTPv2,GTP<ICMP> ping req.

note right #5C8001
**gNB to UPF**
end note

"UE_3" -> "8.8.8.8": 3946, ICMP ping req.

note right #5C8001
**UE_3 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 3947, ICMP ping req.

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 3948, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_3": 3949, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UE_3**
end note

"UPF" -> "gNB": 3950, GTPv2,GTP<ICMP> ping rsp.

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 3953, GTPv2,GTP<ICMP> ping req.

note right #5C8001
**gNB to UPF**
end note

"UE_3" -> "8.8.8.8": 3954, ICMP ping req.

note right #5C8001
**UE_3 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 3955, ICMP ping req.

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 3956, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_3": 3957, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UE_3**
end note

"UPF" -> "gNB": 3958, GTPv2,GTP<ICMP> ping rsp.

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 3959, GTPv2,GTP<ICMP> ping req.

note right #5C8001
**gNB to UPF**
end note

"UE_3" -> "8.8.8.8": 3960, ICMP ping req.

note right #5C8001
**UE_3 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 3961, ICMP ping req.

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 3962, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_3": 3963, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UE_3**
end note

"UPF" -> "gNB": 3964, GTPv2,GTP<ICMP> ping rsp.

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 3965, GTPv2,GTP<ICMP> ping req.

note right #5C8001
**gNB to UPF**
end note

"10.45.0.5" -> "8.8.8.8": 3966, ICMP ping req.

note right #5C8001
**10.45.0.5 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 3967, ICMP ping req.

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 3968, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "10.45.0.5": 3969, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to 10.45.0.5**
end note

"UPF" -> "gNB": 3970, GTPv2,GTP<ICMP> ping rsp.

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 3982, GTPv2,GTP<ICMP> ping req.

note right #5C8001
**gNB to UPF**
end note

"10.45.0.5" -> "8.8.8.8": 3983, ICMP ping req.

note right #5C8001
**10.45.0.5 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 3984, ICMP ping req.

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 3985, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "10.45.0.5": 3986, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to 10.45.0.5**
end note

"UPF" -> "gNB": 3987, GTPv2,GTP<ICMP> ping rsp.

note right #EDFEC2
**UPF to gNB**
end note

"NRF" -> "NRF": 3992, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 3993, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 3995, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"gNB" -> "UPF": 4024, GTPv2,GTP<ICMP> ping req.

note right #5C8001
**gNB to UPF**
end note

"10.45.0.5" -> "8.8.8.8": 4025, ICMP ping req.

note right #5C8001
**10.45.0.5 to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 4026, ICMP ping req.

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 4027, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "10.45.0.5": 4028, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to 10.45.0.5**
end note

"UPF" -> "gNB": 4029, GTPv2,GTP<ICMP> ping rsp.

note right #EDFEC2
**UPF to gNB**
end note

"NRF" -> "NRF": 4032, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4033, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4035, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4039, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4040, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

@enduml
