@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "UE_1"
participant "UE_2"
participant "UE_3"
participant "gNB"
participant "SMF"
participant "UPF"
participant "NRF"
participant "BSF"
participant "10.45.0.5"
participant "PCF"
participant "8.8.8.8"

"8.8.8.8" -> "UPF": 4679, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "UE_3": 4680, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UE_3**
end note

"UPF" -> "gNB": 4681, GTPv2,GTP<ICMP> ping rsp.

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 4682, GTPv2,GTP<ICMP> ping req.

note right #5C8001
**gNB to UPF**
end note

"gNB" -> "UPF": 4683, GTPv2,GTP<ICMP> ping req.

note right #5C8001
**gNB to UPF**
end note

"gNB" -> "UPF": 4721, GTPv2,GTP<ICMP> ping req.

note right #5C8001
**gNB to UPF**
end note

"gNB" -> "UPF": 4722, GTPv2,GTP<ICMP> ping req.

note right #5C8001
**gNB to UPF**
end note

"gNB" -> "UPF": 4733, GTPv2,GTP<ICMP> ping req.

note right #5C8001
**gNB to UPF**
end note

"NRF" -> "NRF": 4741, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4742, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4744, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4746, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4747, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4749, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4780, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4781, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4783, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4785, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4786, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4788, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4790, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4791, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4793, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4795, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4796, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4798, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4800, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4801, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4803, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4805, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4806, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4808, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4885, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4886, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4888, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4900, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4901, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4903, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4909, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4910, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4914, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4916, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4917, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4919, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4945, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4946, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4948, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4950, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4951, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4953, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4955, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4956, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4958, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4960, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4961, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 4963, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5030, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5031, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5033, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5035, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5036, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5038, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5042, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5043, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5045, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5047, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5048, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5050, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5081, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5082, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5084, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5086, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5087, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5089, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5091, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5092, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5094, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5096, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5097, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5099, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5158, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5159, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5161, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5171, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5172, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5174, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5180, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5181, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5183, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5189, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5190, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5192, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5199, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5200, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5202, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5228, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5229, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5231, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5233, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5234, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

@enduml
