@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "UE_1"
participant "UE_2"
participant "UE_3"
participant "gNB"
participant "SMF"
participant "UPF"
participant "NRF"
participant "BSF"
participant "10.45.0.5"
participant "PCF"
participant "8.8.8.8"

"NRF" -> "NRF": 5236, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5238, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5239, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5241, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5296, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5297, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5299, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5309, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5310, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5312, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5316, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5317, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5319, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5321, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5322, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5324, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5334, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5335, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5337, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5366, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5367, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5369, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5371, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5372, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5374, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5376, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5377, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5379, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5444, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5445, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5447, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5463, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5464, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5466, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5475, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5476, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5478, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5487, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5488, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5490, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5498, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5499, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5501, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5503, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5504, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5506, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5508, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5509, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5511, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5517, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5518, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5520, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5634, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5635, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5637, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5643, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5644, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5646, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5652, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5653, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5655, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5657, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5658, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5660, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5664, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5665, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5667, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5669, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5670, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5672, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5674, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5675, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5677, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5679, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5680, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

"NRF" -> "NRF": 5682, HTTP/2 req. or rsp. (no HTTP/2 headers)

note right #03B5AA
**NRF to NRF**
end note

@enduml
