@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "SMF"
participant "UPF"
participant "UPF_2"
participant "SGWU"
participant "SGWC"

"SGWC" -> "SGWU": 155, PFCP req.\nPFCP Association Setup Request (5)

note right #03B5AA
**SGWC to SGWU**
end note

"SGWU" -> "SGWC": 156, PFCP rsp.\nPFCP Association Setup Response (6)

note right #D7FEFC
**SGWU to SGWC**
end note

"SMF" -> "UPF": 646, PFCP req.\nPFCP Association Setup Request (5)

note right #03B5AA
**SMF to UPF**
end note

"UPF" -> "SMF": 647, PFCP rsp.\nPFCP Association Setup Response (6)

note right #D7FEFC
**UPF to SMF**
end note

"SMF" -> "UPF_2": 714, PFCP req.\nPFCP Association Setup Request (5)

note right #03B5AA
**SMF to UPF_2**
end note

"UPF_2" -> "SMF": 715, PFCP rsp.\nPFCP Association Setup Response (6)

note right #D7FEFC
**UPF_2 to SMF**
end note

@enduml
