@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "AUSF"
participant "PCRF"
participant "NRF"
participant "BSF"
participant "HSS"
participant "MME"
participant "10.0.2.14"
participant "PCF"
participant "UDR"
participant "UDM"

"NRF" -> "NRF": 5209, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.671s (16:53:45.580.64)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5211, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.786s (16:53:45.696.247)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5212, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.786s (16:53:45.696.28)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5214, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.786s (16:53:45.696.537)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5216, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.826s (16:53:45.736.275)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5217, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.826s (16:53:45.736.309)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5219, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.826s (16:53:45.736.574)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5250, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.278s (16:53:55.188.274)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5251, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.278s (16:53:55.188.308)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5253, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.278s (16:53:55.188.57)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5260, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.346s (16:53:55.256.278)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5261, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.346s (16:53:55.256.314)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5263, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.347s (16:53:55.256.635)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5265, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.382s (16:53:55.292.262)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5266, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.382s (16:53:55.292.296)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5268, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.383s (16:53:55.292.633)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5270, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.554s (16:53:55.464.555)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5271, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.555s (16:53:55.464.667)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5273, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.555s (16:53:55.464.992)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5275, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.595s (16:53:55.504.709)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5276, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.595s (16:53:55.504.76)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5278, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.595s (16:53:55.505.163)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5280, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.678s (16:53:55.588.257)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5281, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.678s (16:53:55.588.285)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5283, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.678s (16:53:55.588.549)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5285, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.795s (16:53:55.704.908)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5286, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.795s (16:53:55.704.94)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5288, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.795s (16:53:55.705.182)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5290, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.834s (16:53:55.744.324)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5291, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.834s (16:53:55.744.355)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5293, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+598.834s (16:53:55.744.586)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5327, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.287s (16:54:5.197.098)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5328, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.287s (16:54:5.197.149)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5330, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.287s (16:54:5.197.572)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5337, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.350s (16:54:5.260.396)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5338, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.350s (16:54:5.260.445)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5340, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.351s (16:54:5.260.767)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5342, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.391s (16:54:5.301.026)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5343, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.391s (16:54:5.301.061)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5345, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.392s (16:54:5.301.881)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5349, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.562s (16:54:5.472.402)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5350, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.562s (16:54:5.472.442)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5352, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.563s (16:54:5.473.037)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5354, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.602s (16:54:5.512.304)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5355, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.602s (16:54:5.512.337)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5357, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.602s (16:54:5.512.576)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5359, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.686s (16:54:5.596.412)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5360, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.686s (16:54:5.596.461)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5362, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.687s (16:54:5.596.864)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5368, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.802s (16:54:5.712.292)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5369, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.802s (16:54:5.712.327)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5371, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.803s (16:54:5.712.591)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5373, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.842s (16:54:5.752.373)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5374, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.842s (16:54:5.752.409)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5376, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+608.843s (16:54:5.753.46)

note right #b3b3b3
**NRF to NRF**
end note

"HSS" -> "MME": 5407, \n+616.173s (16:54:13.83.281)

note right
**HSS to MME**
end note

"MME" -> "HSS": 5408, \n+616.173s (16:54:13.83.519)

note right
**MME to HSS**
end note

"PCRF" -> "SMF": 5418, \n+616.470s (16:54:13.380.416)

note right
**PCRF to SMF**
end note

"SMF" -> "PCRF": 5419, \n+616.471s (16:54:13.380.656)

note right
**SMF to PCRF**
end note

"NRF" -> "NRF": 5421, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.295s (16:54:15.205.075)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5422, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.295s (16:54:15.205.125)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5424, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.295s (16:54:15.205.513)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5431, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.354s (16:54:15.264.408)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5432, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.354s (16:54:15.264.458)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5434, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.355s (16:54:15.264.786)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5436, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.398s (16:54:15.308.267)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5437, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.398s (16:54:15.308.3)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5439, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.398s (16:54:15.308.538)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5441, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.570s (16:54:15.480.364)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5442, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.570s (16:54:15.480.397)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5444, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.571s (16:54:15.480.651)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5446, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.610s (16:54:15.520.449)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5447, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.610s (16:54:15.520.486)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5449, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.611s (16:54:15.520.731)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5451, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.695s (16:54:15.604.942)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5452, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.695s (16:54:15.604.973)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5454, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.695s (16:54:15.605.231)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5456, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.810s (16:54:15.720.308)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5457, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.810s (16:54:15.720.341)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5459, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.811s (16:54:15.720.596)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5461, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.850s (16:54:15.760.508)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5462, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.850s (16:54:15.760.554)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5464, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+618.851s (16:54:15.760.994)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5495, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.302s (16:54:25.212.462)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5496, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.302s (16:54:25.212.507)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5498, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.303s (16:54:25.212.872)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5505, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.359s (16:54:25.269.294)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5506, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.360s (16:54:25.270.11)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5508, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.361s (16:54:25.270.69)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5510, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.406s (16:54:25.316.516)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5511, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.407s (16:54:25.316.598)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5513, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.407s (16:54:25.317.313)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5515, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.578s (16:54:25.488.376)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5516, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.578s (16:54:25.488.427)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5518, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.579s (16:54:25.489.232)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5520, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.618s (16:54:25.528.498)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5521, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.618s (16:54:25.528.558)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5523, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.619s (16:54:25.528.984)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5525, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.706s (16:54:25.615.743)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5526, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.706s (16:54:25.615.775)

note right #b3b3b3
**NRF to NRF**
end note

@enduml
