@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "AUSF"
participant "PCRF"
participant "NRF"
participant "BSF"
participant "HSS"
participant "MME"
participant "10.0.2.14"
participant "PCF"
participant "UDR"
participant "UDM"

"NRF" -> "NRF": 4884, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.795s (16:53:5.705.048)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4886, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.795s (16:53:5.705.451)

note right #b3b3b3
**NRF to NRF**
end note

"MME" -> "HSS": 4921, \n+557.434s (16:53:14.343.74)

note right
**MME to HSS**
end note

"HSS" -> "MME": 4922, \n+557.434s (16:53:14.343.896)

note right
**HSS to MME**
end note

"SMF" -> "PCRF": 4924, \n+557.731s (16:53:14.640.945)

note right
**SMF to PCRF**
end note

"PCRF" -> "SMF": 4925, \n+557.731s (16:53:14.641.09)

note right
**PCRF to SMF**
end note

"NRF" -> "NRF": 4927, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.238s (16:53:15.148.398)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4928, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.238s (16:53:15.148.454)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4930, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.239s (16:53:15.148.864)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4937, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.332s (16:53:15.242.563)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4938, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.333s (16:53:15.242.625)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4940, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.333s (16:53:15.243.028)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4942, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.350s (16:53:15.260.47)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4943, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.350s (16:53:15.260.544)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4945, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.351s (16:53:15.261.385)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4947, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.520s (16:53:15.429.754)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4948, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.520s (16:53:15.430.046)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4950, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.520s (16:53:15.430.47)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4952, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.559s (16:53:15.469.347)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4953, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.559s (16:53:15.469.399)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4955, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.560s (16:53:15.469.806)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4957, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.640s (16:53:15.549.874)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4958, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.640s (16:53:15.549.898)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4960, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.676s (16:53:15.586.065)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4961, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.686s (16:53:15.596.245)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4964, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.762s (16:53:15.672.499)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4965, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.762s (16:53:15.672.55)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4967, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.763s (16:53:15.672.935)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4969, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.802s (16:53:15.712.481)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4970, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.802s (16:53:15.712.558)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4972, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+558.804s (16:53:15.713.806)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5013, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.248s (16:53:25.158.428)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5014, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.248s (16:53:25.158.52)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5016, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.249s (16:53:25.158.948)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5023, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.335s (16:53:25.244.885)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5024, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.335s (16:53:25.245.075)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5026, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.336s (16:53:25.245.79)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5028, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.358s (16:53:25.268.268)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5029, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.358s (16:53:25.268.3)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5031, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.359s (16:53:25.268.714)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5033, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.526s (16:53:25.436.305)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5034, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.526s (16:53:25.436.342)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5036, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.527s (16:53:25.436.613)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5038, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.566s (16:53:25.476.355)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5039, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.566s (16:53:25.476.411)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5041, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.567s (16:53:25.476.859)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5043, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.646s (16:53:25.556.429)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5045, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.646s (16:53:25.556.496)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5047, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.648s (16:53:25.557.703)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5049, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.770s (16:53:25.680.27)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5050, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.770s (16:53:25.680.302)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5052, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.770s (16:53:25.680.54)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5054, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.810s (16:53:25.720.279)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5055, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.810s (16:53:25.720.313)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5057, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+568.811s (16:53:25.720.743)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5090, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.258s (16:53:35.168.384)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5091, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.258s (16:53:35.168.428)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5093, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.259s (16:53:35.168.689)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5102, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.336s (16:53:35.245.787)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5103, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.336s (16:53:35.245.821)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5105, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.336s (16:53:35.246.078)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5107, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.366s (16:53:35.276.308)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5108, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.366s (16:53:35.276.349)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5110, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.367s (16:53:35.276.638)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5112, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.534s (16:53:35.444.27)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5113, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.534s (16:53:35.444.303)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5115, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.534s (16:53:35.444.555)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5117, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.574s (16:53:35.484.256)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5118, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.574s (16:53:35.484.288)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5120, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.574s (16:53:35.484.546)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5122, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.654s (16:53:35.564.261)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5123, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.654s (16:53:35.564.293)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5125, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.654s (16:53:35.564.538)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5127, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.779s (16:53:35.689.132)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5128, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.779s (16:53:35.689.227)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5130, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.779s (16:53:35.689.462)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5132, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.818s (16:53:35.728.251)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5133, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.818s (16:53:35.728.281)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5135, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+578.818s (16:53:35.728.517)

note right #b3b3b3
**NRF to NRF**
end note

"HSS" -> "MME": 5170, \n+587.909s (16:53:44.818.643)

note right
**HSS to MME**
end note

"MME" -> "HSS": 5171, \n+587.909s (16:53:44.818.798)

note right
**MME to HSS**
end note

"PCRF" -> "SMF": 5173, \n+588.206s (16:53:45.115.85)

note right
**PCRF to SMF**
end note

"SMF" -> "PCRF": 5174, \n+588.206s (16:53:45.116.012)

note right
**SMF to PCRF**
end note

"NRF" -> "NRF": 5175, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.268s (16:53:45.178.031)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5176, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.268s (16:53:45.178.192)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5178, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.270s (16:53:45.180.242)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5185, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.342s (16:53:45.252.502)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5186, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.342s (16:53:45.252.546)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5188, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.343s (16:53:45.252.811)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5190, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.374s (16:53:45.284.277)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5191, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.374s (16:53:45.284.307)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5193, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.374s (16:53:45.284.54)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5196, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.585s (16:53:45.494.812)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5197, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.585s (16:53:45.494.846)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5199, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.585s (16:53:45.495.088)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5201, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.589s (16:53:45.499.41)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5202, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.590s (16:53:45.500.268)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5204, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.591s (16:53:45.500.846)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5206, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.669s (16:53:45.579.556)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5207, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+588.670s (16:53:45.579.606)

note right #b3b3b3
**NRF to NRF**
end note

@enduml
