@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "AUSF"
participant "PCRF"
participant "NRF"
participant "BSF"
participant "HSS"
participant "MME"
participant "10.0.2.14"
participant "PCF"
participant "UDR"
participant "UDM"

"SMF" -> "PCRF": 4206, \n+471.638s (16:51:48.548.532)

note right
**SMF to PCRF**
end note

"PCRF" -> "SMF": 4207, \n+471.639s (16:51:48.548.68)

note right
**PCRF to SMF**
end note

"NRF" -> "NRF": 4237, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.175s (16:51:55.84.606)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4238, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.175s (16:51:55.84.767)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4240, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.175s (16:51:55.85.027)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4247, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.286s (16:51:55.196.406)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4248, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.286s (16:51:55.196.455)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4250, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.287s (16:51:55.196.873)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4252, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.310s (16:51:55.220.272)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4253, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.310s (16:51:55.220.305)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4255, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.310s (16:51:55.220.553)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4257, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.454s (16:51:55.364.587)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4258, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.455s (16:51:55.364.676)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4260, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.455s (16:51:55.365.108)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4262, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.487s (16:51:55.396.821)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4263, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.487s (16:51:55.396.843)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4265, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.487s (16:51:55.397.255)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4267, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.522s (16:51:55.432.022)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4268, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.522s (16:51:55.432.063)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4270, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.523s (16:51:55.433.295)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4272, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.695s (16:51:55.604.973)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4273, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.695s (16:51:55.605.007)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4275, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.695s (16:51:55.605.254)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4277, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.738s (16:51:55.648.269)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4278, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.738s (16:51:55.648.3)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4280, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+478.738s (16:51:55.648.541)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4319, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.182s (16:52:5.92.33)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4320, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.182s (16:52:5.92.362)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4322, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.183s (16:52:5.92.773)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4329, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.295s (16:52:5.205.33)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4330, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.295s (16:52:5.205.388)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4332, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.296s (16:52:5.206.11)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4334, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.314s (16:52:5.224.265)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4335, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.314s (16:52:5.224.303)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4337, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.315s (16:52:5.224.679)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4339, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.462s (16:52:5.372.393)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4340, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.462s (16:52:5.372.432)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4342, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.463s (16:52:5.372.692)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4344, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.494s (16:52:5.404.457)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4345, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.494s (16:52:5.404.492)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4347, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.495s (16:52:5.404.752)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4349, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.533s (16:52:5.442.593)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4350, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.533s (16:52:5.443.223)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4352, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.533s (16:52:5.443.466)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4354, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.702s (16:52:5.612.583)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4355, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.703s (16:52:5.612.771)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4357, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.704s (16:52:5.614.125)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4359, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.746s (16:52:5.656.536)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4360, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.746s (16:52:5.656.584)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4362, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+488.747s (16:52:5.657.055)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4389, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.190s (16:52:15.100.288)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4390, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.190s (16:52:15.100.324)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4392, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.191s (16:52:15.100.597)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4399, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.302s (16:52:15.212.419)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4400, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.302s (16:52:15.212.552)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4402, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.303s (16:52:15.213.105)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4404, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.318s (16:52:15.228.309)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4405, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.318s (16:52:15.228.324)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4407, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.319s (16:52:15.228.605)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4411, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.470s (16:52:15.380.354)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4412, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.470s (16:52:15.380.386)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4414, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.471s (16:52:15.380.627)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4416, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.505s (16:52:15.415.11)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4417, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.505s (16:52:15.415.146)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4419, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.505s (16:52:15.415.398)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4421, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.538s (16:52:15.448.307)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4422, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.538s (16:52:15.448.341)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4424, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.539s (16:52:15.448.612)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4426, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.710s (16:52:15.620.584)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4427, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.711s (16:52:15.620.645)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4429, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.711s (16:52:15.621.114)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4431, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.754s (16:52:15.664.362)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4432, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.754s (16:52:15.664.393)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4434, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+498.755s (16:52:15.664.634)

note right #b3b3b3
**NRF to NRF**
end note

"HSS" -> "MME": 4442, \n+500.231s (16:52:17.140.911)

note right
**HSS to MME**
end note

"MME" -> "HSS": 4443, \n+500.231s (16:52:17.141.149)

note right
**MME to HSS**
end note

"PCRF" -> "SMF": 4449, \n+500.529s (16:52:17.438.888)

note right
**PCRF to SMF**
end note

"SMF" -> "PCRF": 4450, \n+500.529s (16:52:17.439.039)

note right
**SMF to PCRF**
end note

"NRF" -> "NRF": 4477, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.198s (16:52:25.108.485)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4478, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.198s (16:52:25.108.538)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4480, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.199s (16:52:25.108.95)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4487, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.310s (16:52:25.220.501)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4488, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.310s (16:52:25.220.551)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4490, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.311s (16:52:25.220.928)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4492, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.322s (16:52:25.232.365)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4493, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.322s (16:52:25.232.38)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4495, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.323s (16:52:25.232.682)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4497, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.478s (16:52:25.388.383)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4498, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.478s (16:52:25.388.416)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4500, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.479s (16:52:25.388.648)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4502, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.514s (16:52:25.424.292)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4503, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.514s (16:52:25.424.331)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4505, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.515s (16:52:25.424.593)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4507, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.546s (16:52:25.456.291)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4508, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.546s (16:52:25.456.322)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4510, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.546s (16:52:25.456.588)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4512, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.718s (16:52:25.628.511)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4513, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.718s (16:52:25.628.552)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4515, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.719s (16:52:25.628.864)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4517, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.762s (16:52:25.672.521)

note right #b3b3b3
**NRF to NRF**
end note

@enduml
