@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "AUSF"
participant "PCRF"
participant "NRF"
participant "BSF"
participant "HSS"
participant "MME"
participant "10.0.2.14"
participant "PCF"
participant "UDR"
participant "UDM"

"NRF" -> "NRF": 1660, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+158.203s (16:46:35.113.314)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1662, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+158.203s (16:46:35.113.55)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1664, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+158.210s (16:46:35.120.286)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1665, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+158.210s (16:46:35.120.318)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1667, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+158.210s (16:46:35.120.575)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1669, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+158.234s (16:46:35.144.392)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1670, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+158.234s (16:46:35.144.427)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1672, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+158.235s (16:46:35.144.818)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1674, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+158.426s (16:46:35.336.365)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1675, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+158.426s (16:46:35.336.4)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1677, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+158.427s (16:46:35.336.648)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1679, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+158.478s (16:46:35.388.293)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1680, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+158.478s (16:46:35.388.324)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1682, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+158.478s (16:46:35.388.555)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1711, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+167.906s (16:46:44.816.486)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1712, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+167.906s (16:46:44.816.538)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1714, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+167.907s (16:46:44.816.956)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1716, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.011s (16:46:44.921.566)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1717, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.012s (16:46:44.921.617)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1719, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.012s (16:46:44.922.047)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1726, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.194s (16:46:45.104.508)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1727, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.194s (16:46:45.104.559)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1729, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.195s (16:46:45.104.946)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1731, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.215s (16:46:45.124.956)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1732, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.215s (16:46:45.125.002)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1733, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.215s (16:46:45.125.566)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1734, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.216s (16:46:45.125.597)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1737, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.216s (16:46:45.126.075)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1739, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.216s (16:46:45.126.127)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1741, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.245s (16:46:45.154.832)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1742, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.245s (16:46:45.154.874)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1744, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.245s (16:46:45.155.368)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1746, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.436s (16:46:45.346.274)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1747, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.436s (16:46:45.346.336)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1749, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.437s (16:46:45.346.844)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1753, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.486s (16:46:45.396.364)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1754, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.486s (16:46:45.396.394)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1756, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+168.487s (16:46:45.396.623)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1796, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+177.914s (16:46:54.824.257)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1797, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+177.914s (16:46:54.824.289)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1799, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+177.915s (16:46:54.824.678)

note right #b3b3b3
**NRF to NRF**
end note

"HSS" -> "MME": 1801, \n+177.920s (16:46:54.830.013)

note right
**HSS to MME**
end note

"MME" -> "HSS": 1802, \n+177.920s (16:46:54.830.441)

note right
**MME to HSS**
end note

"NRF" -> "NRF": 1805, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.022s (16:46:54.932.291)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1806, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.022s (16:46:54.932.329)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1808, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.023s (16:46:54.932.621)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1816, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.203s (16:46:55.113.311)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1817, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.203s (16:46:55.113.344)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1819, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.204s (16:46:55.114.245)

note right #b3b3b3
**NRF to NRF**
end note

"PCRF" -> "SMF": 1821, \n+178.214s (16:46:55.124.495)

note right
**PCRF to SMF**
end note

"SMF" -> "PCRF": 1822, \n+178.215s (16:46:55.124.797)

note right
**SMF to PCRF**
end note

"NRF" -> "NRF": 1823, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.219s (16:46:55.129.338)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1824, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.219s (16:46:55.129.388)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1826, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.220s (16:46:55.129.711)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1828, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.222s (16:46:55.132.495)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1829, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.222s (16:46:55.132.535)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1831, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.223s (16:46:55.132.773)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1833, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.255s (16:46:55.165.017)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1834, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.255s (16:46:55.165.175)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1836, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.256s (16:46:55.165.8)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1839, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.446s (16:46:55.356.33)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1840, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.446s (16:46:55.356.37)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1842, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.447s (16:46:55.356.627)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1844, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.495s (16:46:55.405.025)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1845, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.495s (16:46:55.405.066)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1847, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+178.495s (16:46:55.405.365)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1882, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+187.922s (16:47:4.832.388)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1883, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+187.922s (16:47:4.832.421)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1885, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+187.923s (16:47:4.832.669)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1887, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.030s (16:47:4.940.301)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1888, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.030s (16:47:4.940.332)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1890, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.030s (16:47:4.940.571)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1897, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.211s (16:47:5.121.227)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1898, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.211s (16:47:5.121.266)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1900, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.215s (16:47:5.125.106)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1902, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.223s (16:47:5.132.755)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1903, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.223s (16:47:5.132.795)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1905, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.224s (16:47:5.134.276)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1907, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.230s (16:47:5.140.331)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1908, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.230s (16:47:5.140.351)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1910, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.231s (16:47:5.140.681)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1912, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.262s (16:47:5.172.33)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1913, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.262s (16:47:5.172.363)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1915, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.263s (16:47:5.172.619)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1917, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.454s (16:47:5.364.269)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1918, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.454s (16:47:5.364.302)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1920, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.454s (16:47:5.364.557)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1922, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.502s (16:47:5.412.281)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1923, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.502s (16:47:5.412.311)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1925, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+188.503s (16:47:5.412.671)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1950, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+197.930s (16:47:14.840.273)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1951, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+197.930s (16:47:14.840.306)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1953, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+197.930s (16:47:14.840.549)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1955, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+198.038s (16:47:14.948.38)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1956, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+198.038s (16:47:14.948.431)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1958, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+198.039s (16:47:14.948.843)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1971, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+198.219s (16:47:15.128.718)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1972, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+198.219s (16:47:15.128.768)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1974, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+198.219s (16:47:15.129.156)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 1976, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+198.225s (16:47:15.135.27)

note right #b3b3b3
**NRF to NRF**
end note

@enduml
