@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "AUSF"
participant "PCRF"
participant "NRF"
participant "BSF"
participant "HSS"
participant "MME"
participant "10.0.2.14"
participant "PCF"
participant "UDR"
participant "UDM"

"NRF" -> "NRF": 4518, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.762s (16:52:25.672.571)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4520, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+508.763s (16:52:25.672.949)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4553, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.206s (16:52:35.116.477)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4554, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.206s (16:52:35.116.529)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4556, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.207s (16:52:35.117.021)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4563, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.318s (16:52:35.228.448)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4564, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.318s (16:52:35.228.503)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4566, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.319s (16:52:35.228.913)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4568, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.326s (16:52:35.236.01)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4569, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.326s (16:52:35.236.064)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4571, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.326s (16:52:35.236.47)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4573, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.486s (16:52:35.396.471)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4574, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.486s (16:52:35.396.522)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4576, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.487s (16:52:35.396.918)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4578, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.522s (16:52:35.432.421)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4579, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.522s (16:52:35.432.472)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4581, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.523s (16:52:35.432.851)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4583, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.554s (16:52:35.464.331)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4584, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.554s (16:52:35.464.372)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4586, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.555s (16:52:35.464.665)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4588, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.727s (16:52:35.636.621)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4589, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.727s (16:52:35.636.685)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4591, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.727s (16:52:35.637.043)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4593, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.770s (16:52:35.680.341)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4594, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.771s (16:52:35.680.627)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4596, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+518.771s (16:52:35.680.921)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4631, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.214s (16:52:45.124.371)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4632, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.214s (16:52:45.124.404)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4634, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.215s (16:52:45.124.647)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4645, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.327s (16:52:45.236.938)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4646, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.327s (16:52:45.236.97)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4647, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.327s (16:52:45.237.084)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4648, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.327s (16:52:45.237.1)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4651, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.328s (16:52:45.237.63)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4653, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.328s (16:52:45.237.71)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4657, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.495s (16:52:45.405.009)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4658, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.495s (16:52:45.405.041)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4660, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.495s (16:52:45.405.315)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4662, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.532s (16:52:45.442.469)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4663, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.532s (16:52:45.442.521)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4665, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.533s (16:52:45.442.912)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4667, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.563s (16:52:45.472.769)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4668, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.563s (16:52:45.472.799)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4670, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.563s (16:52:45.473.092)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4672, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.736s (16:52:45.645.905)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4673, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.736s (16:52:45.645.938)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4675, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.736s (16:52:45.646.183)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4677, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.779s (16:52:45.688.609)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4678, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.779s (16:52:45.688.708)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4680, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+528.779s (16:52:45.688.957)

note right #b3b3b3
**NRF to NRF**
end note

"HSS" -> "MME": 4682, \n+528.942s (16:52:45.851.751)

note right
**HSS to MME**
end note

"MME" -> "HSS": 4683, \n+528.942s (16:52:45.851.897)

note right
**MME to HSS**
end note

"PCRF" -> "SMF": 4685, \n+529.239s (16:52:46.148.958)

note right
**PCRF to SMF**
end note

"SMF" -> "PCRF": 4686, \n+529.239s (16:52:46.149.107)

note right
**SMF to PCRF**
end note

"NRF" -> "NRF": 4713, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.223s (16:52:55.132.886)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4714, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.223s (16:52:55.132.92)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4716, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.223s (16:52:55.133.396)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4723, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.327s (16:52:55.237.119)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4724, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.327s (16:52:55.237.154)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4726, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.327s (16:52:55.237.399)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4728, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.335s (16:52:55.245.117)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4729, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.335s (16:52:55.245.155)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4731, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.335s (16:52:55.245.414)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4733, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.503s (16:52:55.413.386)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4734, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.503s (16:52:55.413.431)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4736, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.504s (16:52:55.413.768)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4738, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.542s (16:52:55.452.269)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4739, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.542s (16:52:55.452.301)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4741, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.543s (16:52:55.452.739)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4743, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.571s (16:52:55.480.817)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4744, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.571s (16:52:55.480.847)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4746, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.571s (16:52:55.481.078)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4748, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.746s (16:52:55.656.248)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4749, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.746s (16:52:55.656.278)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4751, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.746s (16:52:55.656.512)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4753, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.787s (16:52:55.697.339)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4754, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.787s (16:52:55.697.404)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4756, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+538.788s (16:52:55.697.8)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4839, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.230s (16:53:5.140.268)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4840, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.230s (16:53:5.140.3)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4842, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.230s (16:53:5.140.545)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4849, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.330s (16:53:5.240.573)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4850, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.331s (16:53:5.240.608)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4852, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.331s (16:53:5.240.888)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4858, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.342s (16:53:5.252.548)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4859, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.342s (16:53:5.252.563)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4861, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.343s (16:53:5.252.927)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4863, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.510s (16:53:5.420.356)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4864, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.510s (16:53:5.420.387)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4866, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.511s (16:53:5.420.634)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4868, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.550s (16:53:5.460.352)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4869, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.550s (16:53:5.460.388)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4871, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.551s (16:53:5.460.661)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4873, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.578s (16:53:5.488.317)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4874, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.578s (16:53:5.488.351)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4876, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.579s (16:53:5.488.758)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4878, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.754s (16:53:5.664.504)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4879, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.754s (16:53:5.664.557)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4881, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.755s (16:53:5.665.137)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4883, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+548.795s (16:53:5.704.996)

note right #b3b3b3
**NRF to NRF**
end note

@enduml
