@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "AUSF"
participant "PCRF"
participant "NRF"
participant "BSF"
participant "HSS"
participant "MME"
participant "10.0.2.14"
participant "PCF"
participant "UDR"
participant "UDM"

"NRF" -> "NRF": 5528, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.706s (16:54:25.616.057)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5530, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.865s (16:54:25.775.356)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5531, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.866s (16:54:25.775.719)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5532, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.866s (16:54:25.775.753)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5534, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.869s (16:54:25.779.2)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5536, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.869s (16:54:25.779.495)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5538, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+628.876s (16:54:25.785.754)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5573, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.311s (16:54:35.220.629)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5574, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.311s (16:54:35.220.69)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5576, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.311s (16:54:35.221.247)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5583, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.362s (16:54:35.271.97)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5584, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.362s (16:54:35.272.013)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5586, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.363s (16:54:35.272.608)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5588, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.415s (16:54:35.325.491)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5589, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.415s (16:54:35.325.547)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5591, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.416s (16:54:35.325.968)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5593, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.586s (16:54:35.496.283)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5594, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.586s (16:54:35.496.317)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5596, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.586s (16:54:35.496.582)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5598, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.626s (16:54:35.536.301)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5599, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.626s (16:54:35.536.343)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5601, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.627s (16:54:35.536.813)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5603, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.717s (16:54:35.626.871)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5604, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.717s (16:54:35.626.966)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5606, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.718s (16:54:35.627.608)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5608, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.874s (16:54:35.784.395)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5609, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.874s (16:54:35.784.447)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5610, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.875s (16:54:35.784.638)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5611, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.875s (16:54:35.784.666)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5614, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.875s (16:54:35.785.383)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5616, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+638.875s (16:54:35.785.432)

note right #b3b3b3
**NRF to NRF**
end note

"MME" -> "HSS": 5633, \n+644.585s (16:54:41.495.319)

note right
**MME to HSS**
end note

"HSS" -> "MME": 5634, \n+644.586s (16:54:41.495.748)

note right
**HSS to MME**
end note

"SMF" -> "PCRF": 5638, \n+644.882s (16:54:41.792.353)

note right
**SMF to PCRF**
end note

"PCRF" -> "SMF": 5639, \n+644.883s (16:54:41.792.81)

note right
**PCRF to SMF**
end note

"NRF" -> "NRF": 5649, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.318s (16:54:45.228.435)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5650, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.318s (16:54:45.228.451)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5652, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.319s (16:54:45.228.74)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5659, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.364s (16:54:45.273.98)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5660, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.364s (16:54:45.274.012)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5662, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.364s (16:54:45.274.239)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5664, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.426s (16:54:45.336.4)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5665, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.426s (16:54:45.336.453)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5667, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.427s (16:54:45.336.908)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5669, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.595s (16:54:45.505.191)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5670, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.595s (16:54:45.505.508)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5672, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.596s (16:54:45.506.104)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5674, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.634s (16:54:45.544.273)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5675, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.634s (16:54:45.544.305)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5677, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.634s (16:54:45.544.555)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5679, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.726s (16:54:45.636.255)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5680, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.726s (16:54:45.636.287)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5682, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.726s (16:54:45.636.533)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5684, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.883s (16:54:45.793.479)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5685, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.885s (16:54:45.794.591)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5686, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.885s (16:54:45.794.66)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5688, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.887s (16:54:45.796.592)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5689, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.891s (16:54:45.801.137)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5692, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+648.896s (16:54:45.806.286)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5751, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.327s (16:54:55.237.027)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5752, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.327s (16:54:55.237.061)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5754, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.327s (16:54:55.237.312)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5761, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.366s (16:54:55.276.28)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5762, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.366s (16:54:55.276.312)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5764, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.366s (16:54:55.276.552)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5770, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.435s (16:54:55.344.825)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5771, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.435s (16:54:55.344.963)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5773, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.436s (16:54:55.345.909)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5781, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.602s (16:54:55.512.435)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5782, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.602s (16:54:55.512.471)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5784, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.603s (16:54:55.512.729)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5786, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.642s (16:54:55.552.297)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5787, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.642s (16:54:55.552.33)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5789, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.642s (16:54:55.552.575)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5793, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.734s (16:54:55.644.414)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5794, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.734s (16:54:55.644.452)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5796, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.735s (16:54:55.644.876)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5798, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.890s (16:54:55.800.308)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5799, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.890s (16:54:55.800.341)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5801, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.891s (16:54:55.800.625)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5803, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.899s (16:54:55.808.963)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5804, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.899s (16:54:55.808.996)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5806, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+658.899s (16:54:55.809.304)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5834, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+668.334s (16:55:5.244.562)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5835, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+668.335s (16:55:5.244.595)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5837, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+668.335s (16:55:5.244.838)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5839, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+668.367s (16:55:5.276.695)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5840, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+668.367s (16:55:5.276.727)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5842, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+668.367s (16:55:5.276.97)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5844, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+668.443s (16:55:5.352.849)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5845, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+668.443s (16:55:5.353.026)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5847, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+668.444s (16:55:5.353.898)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5849, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+668.610s (16:55:5.520.339)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5850, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+668.610s (16:55:5.520.376)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5852, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+668.611s (16:55:5.520.648)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5854, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+668.650s (16:55:5.560.266)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5855, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+668.650s (16:55:5.560.3)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5857, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+668.650s (16:55:5.560.536)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5859, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+668.743s (16:55:5.652.594)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 5860, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+668.743s (16:55:5.652.626)

note right #b3b3b3
**NRF to NRF**
end note

@enduml
