@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "AUSF"
participant "PCRF"
participant "NRF"
participant "BSF"
participant "HSS"
participant "MME"
participant "10.0.2.14"
participant "PCF"
participant "UDR"
participant "UDM"

"NRF" -> "NRF": 3911, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.143s (16:51:15.52.778)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3918, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.250s (16:51:15.160.342)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3919, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.250s (16:51:15.160.375)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3921, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.251s (16:51:15.160.695)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3923, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.298s (16:51:15.208.346)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3924, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.298s (16:51:15.208.377)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3927, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.299s (16:51:15.208.785)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3932, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.418s (16:51:15.328.273)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3933, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.418s (16:51:15.328.305)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3935, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.418s (16:51:15.328.549)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3937, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.454s (16:51:15.364.453)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3938, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.454s (16:51:15.364.488)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3940, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.455s (16:51:15.364.75)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3942, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.486s (16:51:15.396.391)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3943, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.486s (16:51:15.396.441)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3945, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.487s (16:51:15.396.996)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3947, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.662s (16:51:15.572.265)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3948, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.662s (16:51:15.572.299)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3950, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.662s (16:51:15.572.531)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3952, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.706s (16:51:15.616.359)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3953, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.706s (16:51:15.616.393)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3955, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+438.707s (16:51:15.616.635)

note right #b3b3b3
**NRF to NRF**
end note

"MME" -> "HSS": 3971, \n+440.863s (16:51:17.772.7)

note right
**MME to HSS**
end note

"HSS" -> "MME": 3972, \n+440.863s (16:51:17.772.874)

note right
**HSS to MME**
end note

"SMF" -> "PCRF": 3974, \n+441.160s (16:51:18.70.366)

note right
**SMF to PCRF**
end note

"PCRF" -> "SMF": 3975, \n+441.161s (16:51:18.71.068)

note right
**PCRF to SMF**
end note

"NRF" -> "NRF": 3994, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.150s (16:51:25.60.244)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3995, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.150s (16:51:25.60.276)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3997, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.150s (16:51:25.60.522)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 3999, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.259s (16:51:25.168.64)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4000, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.259s (16:51:25.168.814)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4002, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.259s (16:51:25.169.554)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4009, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.301s (16:51:25.210.904)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4010, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.301s (16:51:25.210.937)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4012, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.302s (16:51:25.212.282)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4014, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.428s (16:51:25.338.297)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4015, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.428s (16:51:25.338.331)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4017, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.428s (16:51:25.338.574)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4019, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.462s (16:51:25.372.361)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4020, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.462s (16:51:25.372.415)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4022, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.463s (16:51:25.372.761)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4024, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.494s (16:51:25.404.48)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4025, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.494s (16:51:25.404.516)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4027, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.495s (16:51:25.404.754)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4029, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.670s (16:51:25.580.274)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4030, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.670s (16:51:25.580.308)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4032, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.670s (16:51:25.580.546)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4034, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.714s (16:51:25.624.298)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4035, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.714s (16:51:25.624.333)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4037, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+448.714s (16:51:25.624.572)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4072, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.159s (16:51:35.68.592)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4073, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.159s (16:51:35.68.625)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4075, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.159s (16:51:35.69.059)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4077, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.266s (16:51:35.176.545)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4078, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.267s (16:51:35.176.605)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4080, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.267s (16:51:35.177.044)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4087, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.304s (16:51:35.213.819)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4088, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.304s (16:51:35.213.866)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4090, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.304s (16:51:35.214.458)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4092, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.438s (16:51:35.348.275)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4093, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.438s (16:51:35.348.308)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4095, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.438s (16:51:35.348.536)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4097, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.470s (16:51:35.380.271)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4098, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.470s (16:51:35.380.307)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4100, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.470s (16:51:35.380.552)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4102, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.503s (16:51:35.413.064)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4103, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.503s (16:51:35.413.321)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4105, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.504s (16:51:35.414.109)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4107, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.678s (16:51:35.588.275)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4108, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.678s (16:51:35.588.308)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4110, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.678s (16:51:35.588.562)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4112, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.722s (16:51:35.632.406)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4113, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.722s (16:51:35.632.477)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4115, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+458.723s (16:51:35.633.332)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4142, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.166s (16:51:45.76.261)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4143, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.166s (16:51:45.76.298)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4145, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.166s (16:51:45.76.556)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4149, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.276s (16:51:45.186.541)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4152, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.277s (16:51:45.187.162)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4154, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.278s (16:51:45.188.114)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4159, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.304s (16:51:45.214.331)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4160, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.304s (16:51:45.214.364)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4162, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.305s (16:51:45.214.607)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4164, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.446s (16:51:45.356.27)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4165, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.446s (16:51:45.356.303)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4167, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.446s (16:51:45.356.556)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4169, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.479s (16:51:45.388.976)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4170, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.479s (16:51:45.389.008)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4172, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.479s (16:51:45.389.258)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4176, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.511s (16:51:45.421.298)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4177, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.511s (16:51:45.421.33)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4179, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.511s (16:51:45.421.585)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4181, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.686s (16:51:45.596.281)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4182, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.686s (16:51:45.596.315)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4184, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.686s (16:51:45.596.558)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4186, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.731s (16:51:45.640.639)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4187, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.731s (16:51:45.640.691)

note right #b3b3b3
**NRF to NRF**
end note

"NRF" -> "NRF": 4189, HTTP/2 req. or rsp. (no HTTP/2 headers)\n+468.731s (16:51:45.641.077)

note right #b3b3b3
**NRF to NRF**
end note

"MME" -> "HSS": 4203, \n+471.340s (16:51:48.250.437)

note right
**MME to HSS**
end note

"HSS" -> "MME": 4204, \n+471.340s (16:51:48.250.581)

note right
**HSS to MME**
end note

@enduml
