@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}

participant "Malicious UE"
participant "gNB"
participant "User Plane Function (UPF)"


"gNB" -> "User Plane Function (UPF)": PFCP req.\nPFCP Association Setup Request (5)

note right #03B5AA
**gNB to UPF**
end note

"Malicious UE" -> "User Plane Function (UPF)":  PFCP req.\nPFCP Association Setup Request (5)

note right #FFC2D9
**gNB to UPF**
end note

"User Plane Function (UPF)" -> "Malicious UE": PFCP rsp.\nPFCP Association Setup Response (6)

note right #FFEAC2
**UPF to Malicious UE**
end note

"User Plane Function (UPF)" -> "gNB": PFCP rsp.\nPFCP Association Setup Response (6)

note right #FFEAC2
**UPF to gNB**
end note

"gNB" -> "User Plane Function (UPF)":  <PORT_UNREACHABLE> PFCP,GTP<ICMP> rsp.\nPFCP Association Setup Response (6)

note right #D7FEFC
**gNB to UPF**
end note

"gNB" -> "User Plane Function (UPF)": PFCP req.\nPFCP Session Deletion Request (54)

note right #03B5AA
**gNB to UPF**
end note

"Malicious UE" -> "User Plane Function (UPF)": PFCP req.\nPFCP Session Deletion Request (54)

note right #FFC2D9
**gNB to UPF**
end note


"User Plane Function (UPF)" -> "Malicious UE": PFCP rsp.\nPFCP Session Deletion Response (55)

note right #FFEAC2
**UPF to Malicious UE**
end note

"User Plane Function (UPF)" -> "gNB": PFCP rsp.\nPFCP Session Deletion Response (55)

note right #FFEAC2
**UPF to gNB**
end note

"gNB" -> "User Plane Function (UPF)": 4345, <PORT_UNREACHABLE> PFCP,GTP<ICMP> rsp.\nPFCP Session Deletion Response (55)

note right #D7FEFC
**gNB to UPF**
end note


@enduml
