@startuml
skinparam shadowing false
skinparam NoteBorderColor white
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor black
    ParticipantBorderColor white
    ParticipantBackgroundColor #e6e6e6
}

participant "Malicious UE"
participant "Targeted UE"
participant "gNB"
participant "AMF"
participant "SMF"
participant "UPF"
participant "SGWU"
participant "SGWC"

participant "8.8.8.8"

"gNB" -> "UPF": 4248, GTP<ICMP> ping req.

note right #5C8001
**gNB to UPF**
end note

"Targeted UE" -> "8.8.8.8": 4249, ICMP ping req.
note right #5C8001
**Targeted UE to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 4250, ICMP ping req.
note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 4251, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "Targeted UE": 4252, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to Targeted UE**
end note

"UPF" -> "gNB": 4253, GTP<ICMP> ping rsp.

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 4335, PFCP req.\nPFCP Association Setup Request (5)

note right #5C8001
**gNB to UPF**
end note

"Malicious UE" -> "UPF": 4335, PFCP req.\nPFCP Association Setup Request (5)

note right #FFC2D9
**gNB to UPF**
end note

"UPF" -> "Malicious UE": 4337, PFCP rsp.\nPFCP Association Setup Response (6)

note right #FFEAC2
**UPF to Malicious UE**
end note

"UPF" -> "gNB": 4338, PFCP rsp.\nPFCP Association Setup Response (6)

note right #FFEAC2
**UPF to gNB**
end note

"gNB" -> "UPF": 4339, <PORT_UNREACHABLE> PFCP,GTP<ICMP> rsp.\nPFCP Association Setup Response (6)

note right #D7FEFC
**gNB to UPF**
end note

"gNB" -> "UPF": 4341, PFCP req.\nPFCP Session Deletion Request (54)

note right #5C8001
**gNB to UPF**
end note

"Malicious UE" -> "UPF": 4341, PFCP req.\nPFCP Session Deletion Request (54)

note right #FFC2D9
**gNB to UPF**
end note


"UPF" -> "Malicious UE": 4343, PFCP rsp.\nPFCP Session Deletion Response (55)

note right #FFEAC2
**UPF to Malicious UE**
end note

"UPF" -> "gNB": 4344, PFCP rsp.\nPFCP Session Deletion Response (55)

note right #FFEAC2
**UPF to gNB**
end note

"gNB" -> "UPF": 4345, <PORT_UNREACHABLE> PFCP,GTP<ICMP> rsp.\nPFCP Session Deletion Response (55)

note right #D7FEFC
**gNB to UPF**
end note

"gNB" -> "UPF": 4406, GTP<ICMP> ping req.

note right #5C8001
**gNB to UPF**
end note

"Malicious UE" -> "8.8.8.8": 4407, ICMP ping req.

note right #5C8001
**Malicious UE to 8.8.8.8**
end note

"UPF" -> "8.8.8.8": 4408, ICMP ping req.

note right #5C8001
**UPF to 8.8.8.8**
end note

"8.8.8.8" -> "UPF": 4409, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to UPF**
end note

"8.8.8.8" -> "Malicious UE": 4410, ICMP ping rsp.

note right #EDFEC2
**8.8.8.8 to Malicious UE**
end note

"UPF" -> "gNB": 4411, GTP<ICMP> ping rsp.

note right #EDFEC2
**UPF to gNB**
end note

"gNB" -> "UPF": 4412, GTP<ICMP> ping req.

note right #5C8001
**gNB to UPF**
end note

@enduml
